version: "3.9"

services:
  aerospike:
    image: aerospike:ce-8.1.1.1
    container_name: utm-track-manager-aerospike
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "asinfo", "-v", "status"]
      interval: 5s
      timeout: 3s
      retries: 10

  nats:
    image: nats:2.12-alpine
    container_name: utm-track-manager-nats
    ports:
      - "4222:4222"
      - "8222:8222"

  utm-track-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDER_IMAGE: golang:1.24.0-bookworm
        TARGET_IMAGE: debian:bookworm-slim
    container_name: utm-track-manager-dev
    depends_on:
      aerospike:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./docker/dev/app.yaml:/utm-track-manager/bin/app.yaml:ro