aerospike:
  host: "localhost"
  port: 3000
  hosts: []
  namespace: "track_manager"
  user: ""
  pass: ""
  connection_queue_size: 100
  min_connections_per_node: 0
  idle_timeout_ms: 0
  connect_timeout_ms: 30000
  tend_interval_ms: 1000
  warm_up_connections: 10
  use_services_alternate: false
http:
  port: 33180
  enable_recover_middleware: true
  enable_cors_middleware: true
  endpoints:
    ms-event-listener: "http://localhost:32080"
    ms-system: "http://localhost:33080"
grpc:
  port: 33165
  channels:
    ms-event-listener: "localhost:32065"
    ms-system: "localhost:33065"
other:
  environment: "development"
  default_lang: "en"
  tracing_host: "localhost"
  tracing_port: 33333
nats:
  server: "localhost:4222"
jwt_token_config:
  validate_jwt: false
