// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: ipc/track/cmd/CommandTypes.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_UNKNOWN CommandType = 0
	// Track command
	CommandType_CREATE_TRACK      CommandType = 2
	CommandType_EDIT_TRACK        CommandType = 3
	CommandType_REMOVE_TRACK      CommandType = 4
	CommandType_CORRELATE_TRACK   CommandType = 5
	CommandType_DECORRELATE_TRACK CommandType = 6
	// Config
	CommandType_ALGO_CONFIG CommandType = 50
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "UNKNOWN",
		2:  "CREATE_TRACK",
		3:  "EDIT_TRACK",
		4:  "REMOVE_TRACK",
		5:  "CORRELATE_TRACK",
		6:  "DECORRELATE_TRACK",
		50: "ALGO_CONFIG",
	}
	CommandType_value = map[string]int32{
		"UNKNOWN":           0,
		"CREATE_TRACK":      2,
		"EDIT_TRACK":        3,
		"REMOVE_TRACK":      4,
		"CORRELATE_TRACK":   5,
		"DECORRELATE_TRACK": 6,
		"ALGO_CONFIG":       50,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_ipc_track_cmd_CommandTypes_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_ipc_track_cmd_CommandTypes_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_ipc_track_cmd_CommandTypes_proto_rawDescGZIP(), []int{0}
}

var File_ipc_track_cmd_CommandTypes_proto protoreflect.FileDescriptor

var file_ipc_track_cmd_CommandTypes_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x8b, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f,
	0x54, 0x52, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x44, 0x49, 0x54, 0x5f,
	0x54, 0x52, 0x41, 0x43, 0x4b, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x52,
	0x52, 0x45, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x10, 0x05, 0x12, 0x15,
	0x0a, 0x11, 0x44, 0x45, 0x43, 0x4f, 0x52, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x52,
	0x41, 0x43, 0x4b, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x43, 0x4f,
	0x4e, 0x46, 0x49, 0x47, 0x10, 0x32, 0x42, 0x3d, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68,
	0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x42, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x05,
	0x2e, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_track_cmd_CommandTypes_proto_rawDescOnce sync.Once
	file_ipc_track_cmd_CommandTypes_proto_rawDescData = file_ipc_track_cmd_CommandTypes_proto_rawDesc
)

func file_ipc_track_cmd_CommandTypes_proto_rawDescGZIP() []byte {
	file_ipc_track_cmd_CommandTypes_proto_rawDescOnce.Do(func() {
		file_ipc_track_cmd_CommandTypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_track_cmd_CommandTypes_proto_rawDescData)
	})
	return file_ipc_track_cmd_CommandTypes_proto_rawDescData
}

var file_ipc_track_cmd_CommandTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ipc_track_cmd_CommandTypes_proto_goTypes = []interface{}{
	(CommandType)(0), // 0: com.vht.bms.messages.CommandType
}
var file_ipc_track_cmd_CommandTypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_track_cmd_CommandTypes_proto_init() }
func file_ipc_track_cmd_CommandTypes_proto_init() {
	if File_ipc_track_cmd_CommandTypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_track_cmd_CommandTypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_track_cmd_CommandTypes_proto_goTypes,
		DependencyIndexes: file_ipc_track_cmd_CommandTypes_proto_depIdxs,
		EnumInfos:         file_ipc_track_cmd_CommandTypes_proto_enumTypes,
	}.Build()
	File_ipc_track_cmd_CommandTypes_proto = out.File
	file_ipc_track_cmd_CommandTypes_proto_rawDesc = nil
	file_ipc_track_cmd_CommandTypes_proto_goTypes = nil
	file_ipc_track_cmd_CommandTypes_proto_depIdxs = nil
}
