// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: ipc/track/cmd/CommandResponseMessage.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response after process CommandContentMessage
type CommandResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId    string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`           // Required. Correspond with the command_id in CommandContentMessage
	ResponseCode int32  `protobuf:"varint,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"` // Response code = 0 => SUCCESS, otherwise is FAILED
	// List of tracks which are updated after performing command (including new tracks, excluding removed tracks)
	Tracks []*TrackMessage `protobuf:"bytes,3,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Detail *ResponseDetail `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CommandResponseMessage) Reset() {
	*x = CommandResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponseMessage) ProtoMessage() {}

func (x *CommandResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponseMessage.ProtoReflect.Descriptor instead.
func (*CommandResponseMessage) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_CommandResponseMessage_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResponseMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponseMessage) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *CommandResponseMessage) GetTracks() []*TrackMessage {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *CommandResponseMessage) GetDetail() *ResponseDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ResponseDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId   string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType int32  `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // Refer to CommandTypes.proto
	Detail      []byte `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`                               // Depend on command type
}

func (x *ResponseDetail) Reset() {
	*x = ResponseDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDetail) ProtoMessage() {}

func (x *ResponseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDetail.ProtoReflect.Descriptor instead.
func (*ResponseDetail) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_CommandResponseMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseDetail) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ResponseDetail) GetCommandType() int32 {
	if x != nil {
		return x.CommandType
	}
	return 0
}

func (x *ResponseDetail) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_ipc_track_cmd_CommandResponseMessage_proto protoreflect.FileDescriptor

var file_ipc_track_cmd_CommandResponseMessage_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f,
	0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x1a, 0x1c, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd6, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x3a, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x3c, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x6a, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x44, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74,
	0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x42, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ipc_track_cmd_CommandResponseMessage_proto_rawDescOnce sync.Once
	file_ipc_track_cmd_CommandResponseMessage_proto_rawDescData = file_ipc_track_cmd_CommandResponseMessage_proto_rawDesc
)

func file_ipc_track_cmd_CommandResponseMessage_proto_rawDescGZIP() []byte {
	file_ipc_track_cmd_CommandResponseMessage_proto_rawDescOnce.Do(func() {
		file_ipc_track_cmd_CommandResponseMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_track_cmd_CommandResponseMessage_proto_rawDescData)
	})
	return file_ipc_track_cmd_CommandResponseMessage_proto_rawDescData
}

var file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_track_cmd_CommandResponseMessage_proto_goTypes = []interface{}{
	(*CommandResponseMessage)(nil), // 0: com.vht.bms.messages.CommandResponseMessage
	(*ResponseDetail)(nil),         // 1: com.vht.bms.messages.ResponseDetail
	(*TrackMessage)(nil),           // 2: com.vht.bms.messages.TrackMessage
}
var file_ipc_track_cmd_CommandResponseMessage_proto_depIdxs = []int32{
	2, // 0: com.vht.bms.messages.CommandResponseMessage.tracks:type_name -> com.vht.bms.messages.TrackMessage
	1, // 1: com.vht.bms.messages.CommandResponseMessage.detail:type_name -> com.vht.bms.messages.ResponseDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ipc_track_cmd_CommandResponseMessage_proto_init() }
func file_ipc_track_cmd_CommandResponseMessage_proto_init() {
	if File_ipc_track_cmd_CommandResponseMessage_proto != nil {
		return
	}
	file_ipc_track_TrackMessage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_track_cmd_CommandResponseMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_track_cmd_CommandResponseMessage_proto_goTypes,
		DependencyIndexes: file_ipc_track_cmd_CommandResponseMessage_proto_depIdxs,
		MessageInfos:      file_ipc_track_cmd_CommandResponseMessage_proto_msgTypes,
	}.Build()
	File_ipc_track_cmd_CommandResponseMessage_proto = out.File
	file_ipc_track_cmd_CommandResponseMessage_proto_rawDesc = nil
	file_ipc_track_cmd_CommandResponseMessage_proto_goTypes = nil
	file_ipc_track_cmd_CommandResponseMessage_proto_depIdxs = nil
}
