// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: ipc/track/cmd/CorrelateTrackCommand.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Correlate second track into first track
type CorrelateTrackCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstTrackId  int32 `protobuf:"varint,1,opt,name=first_track_id,json=firstTrackId,proto3" json:"first_track_id,omitempty"`
	SecondTrackId int32 `protobuf:"varint,2,opt,name=second_track_id,json=secondTrackId,proto3" json:"second_track_id,omitempty"`
}

func (x *CorrelateTrackCommand) Reset() {
	*x = CorrelateTrackCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrelateTrackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelateTrackCommand) ProtoMessage() {}

func (x *CorrelateTrackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelateTrackCommand.ProtoReflect.Descriptor instead.
func (*CorrelateTrackCommand) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescGZIP(), []int{0}
}

func (x *CorrelateTrackCommand) GetFirstTrackId() int32 {
	if x != nil {
		return x.FirstTrackId
	}
	return 0
}

func (x *CorrelateTrackCommand) GetSecondTrackId() int32 {
	if x != nil {
		return x.SecondTrackId
	}
	return 0
}

// De-correlate a source track of a system track. After de-correlation, the source track will become:
// (1) a new system track, or
// (2) source-track of another system track
//
// For example: system track id 1000 de-correlate a source track (source 30, id 50)
// Ex1: Source track become new system track => Message details:
//          track_id = 1000
//          source_id = 30
//          source_track_id = 50
//
// Ex2: Source track become source track of track id 1001 => Message details:
//          track_id = 1000
//          source_id = 30
//          source_track_id = 50
//          target_track_id = 1001
type DecorrelateTrackCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId       int32  `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceTrackId int32  `protobuf:"varint,3,opt,name=source_track_id,json=sourceTrackId,proto3" json:"source_track_id,omitempty"`
	// If target_track_id = 0, source track will become a new system track,
	// else source track will be correlated into target track (if possible)
	TargetTrackId int32 `protobuf:"varint,4,opt,name=target_track_id,json=targetTrackId,proto3" json:"target_track_id,omitempty"`
}

func (x *DecorrelateTrackCommand) Reset() {
	*x = DecorrelateTrackCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecorrelateTrackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecorrelateTrackCommand) ProtoMessage() {}

func (x *DecorrelateTrackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecorrelateTrackCommand.ProtoReflect.Descriptor instead.
func (*DecorrelateTrackCommand) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescGZIP(), []int{1}
}

func (x *DecorrelateTrackCommand) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *DecorrelateTrackCommand) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DecorrelateTrackCommand) GetSourceTrackId() int32 {
	if x != nil {
		return x.SourceTrackId
	}
	return 0
}

func (x *DecorrelateTrackCommand) GetTargetTrackId() int32 {
	if x != nil {
		return x.TargetTrackId
	}
	return 0
}

var File_ipc_track_cmd_CorrelateTrackCommand_proto protoreflect.FileDescriptor

var file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x65, 0x0a, 0x15, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x17, 0x44, 0x65, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x42, 0x43, 0x0a, 0x1e,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x42, 0x1a,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescOnce sync.Once
	file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescData = file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDesc
)

func file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescGZIP() []byte {
	file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescOnce.Do(func() {
		file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescData)
	})
	return file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDescData
}

var file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_track_cmd_CorrelateTrackCommand_proto_goTypes = []interface{}{
	(*CorrelateTrackCommand)(nil),   // 0: com.vht.bms.messages.CorrelateTrackCommand
	(*DecorrelateTrackCommand)(nil), // 1: com.vht.bms.messages.DecorrelateTrackCommand
}
var file_ipc_track_cmd_CorrelateTrackCommand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_track_cmd_CorrelateTrackCommand_proto_init() }
func file_ipc_track_cmd_CorrelateTrackCommand_proto_init() {
	if File_ipc_track_cmd_CorrelateTrackCommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrelateTrackCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecorrelateTrackCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_track_cmd_CorrelateTrackCommand_proto_goTypes,
		DependencyIndexes: file_ipc_track_cmd_CorrelateTrackCommand_proto_depIdxs,
		MessageInfos:      file_ipc_track_cmd_CorrelateTrackCommand_proto_msgTypes,
	}.Build()
	File_ipc_track_cmd_CorrelateTrackCommand_proto = out.File
	file_ipc_track_cmd_CorrelateTrackCommand_proto_rawDesc = nil
	file_ipc_track_cmd_CorrelateTrackCommand_proto_goTypes = nil
	file_ipc_track_cmd_CorrelateTrackCommand_proto_depIdxs = nil
}
