// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: ipc/track/cmd/GroupTrackCommand.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupTrackCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId        int32   `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	AddingGroups   []int32 `protobuf:"varint,2,rep,packed,name=adding_groups,json=addingGroups,proto3" json:"adding_groups,omitempty"`
	RemovingGroups []int32 `protobuf:"varint,3,rep,packed,name=removing_groups,json=removingGroups,proto3" json:"removing_groups,omitempty"`
}

func (x *GroupTrackCommand) Reset() {
	*x = GroupTrackCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTrackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTrackCommand) ProtoMessage() {}

func (x *GroupTrackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTrackCommand.ProtoReflect.Descriptor instead.
func (*GroupTrackCommand) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_GroupTrackCommand_proto_rawDescGZIP(), []int{0}
}

func (x *GroupTrackCommand) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *GroupTrackCommand) GetAddingGroups() []int32 {
	if x != nil {
		return x.AddingGroups
	}
	return nil
}

func (x *GroupTrackCommand) GetRemovingGroups() []int32 {
	if x != nil {
		return x.RemovingGroups
	}
	return nil
}

type GroupTrackCommandV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId        int32   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AddingTracks   []int32 `protobuf:"varint,2,rep,packed,name=adding_tracks,json=addingTracks,proto3" json:"adding_tracks,omitempty"`
	RemovingTracks []int32 `protobuf:"varint,3,rep,packed,name=removing_tracks,json=removingTracks,proto3" json:"removing_tracks,omitempty"`
}

func (x *GroupTrackCommandV2) Reset() {
	*x = GroupTrackCommandV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTrackCommandV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTrackCommandV2) ProtoMessage() {}

func (x *GroupTrackCommandV2) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTrackCommandV2.ProtoReflect.Descriptor instead.
func (*GroupTrackCommandV2) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_GroupTrackCommand_proto_rawDescGZIP(), []int{1}
}

func (x *GroupTrackCommandV2) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupTrackCommandV2) GetAddingTracks() []int32 {
	if x != nil {
		return x.AddingTracks
	}
	return nil
}

func (x *GroupTrackCommandV2) GetRemovingTracks() []int32 {
	if x != nil {
		return x.RemovingTracks
	}
	return nil
}

var File_ipc_track_cmd_GroupTrackCommand_proto protoreflect.FileDescriptor

var file_ipc_track_cmd_GroupTrackCommand_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74,
	0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x7c, 0x0a,
	0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x7e, 0x0a, 0x13, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x56, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x42, 0x3f, 0x0a, 0x1e, 0x63,
	0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x42, 0x16, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_track_cmd_GroupTrackCommand_proto_rawDescOnce sync.Once
	file_ipc_track_cmd_GroupTrackCommand_proto_rawDescData = file_ipc_track_cmd_GroupTrackCommand_proto_rawDesc
)

func file_ipc_track_cmd_GroupTrackCommand_proto_rawDescGZIP() []byte {
	file_ipc_track_cmd_GroupTrackCommand_proto_rawDescOnce.Do(func() {
		file_ipc_track_cmd_GroupTrackCommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_track_cmd_GroupTrackCommand_proto_rawDescData)
	})
	return file_ipc_track_cmd_GroupTrackCommand_proto_rawDescData
}

var file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipc_track_cmd_GroupTrackCommand_proto_goTypes = []interface{}{
	(*GroupTrackCommand)(nil),   // 0: com.vht.bms.messages.GroupTrackCommand
	(*GroupTrackCommandV2)(nil), // 1: com.vht.bms.messages.GroupTrackCommandV2
}
var file_ipc_track_cmd_GroupTrackCommand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_track_cmd_GroupTrackCommand_proto_init() }
func file_ipc_track_cmd_GroupTrackCommand_proto_init() {
	if File_ipc_track_cmd_GroupTrackCommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTrackCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTrackCommandV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_track_cmd_GroupTrackCommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_track_cmd_GroupTrackCommand_proto_goTypes,
		DependencyIndexes: file_ipc_track_cmd_GroupTrackCommand_proto_depIdxs,
		MessageInfos:      file_ipc_track_cmd_GroupTrackCommand_proto_msgTypes,
	}.Build()
	File_ipc_track_cmd_GroupTrackCommand_proto = out.File
	file_ipc_track_cmd_GroupTrackCommand_proto_rawDesc = nil
	file_ipc_track_cmd_GroupTrackCommand_proto_goTypes = nil
	file_ipc_track_cmd_GroupTrackCommand_proto_depIdxs = nil
}
