// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: PositionAndVelocity.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dimension int32

const (
	Dimension_DIMENSION_2D Dimension = 0
	Dimension_DIMENSION_3D Dimension = 1
)

// Enum value maps for Dimension.
var (
	Dimension_name = map[int32]string{
		0: "DIMENSION_2D",
		1: "DIMENSION_3D",
	}
	Dimension_value = map[string]int32{
		"DIMENSION_2D": 0,
		"DIMENSION_3D": 1,
	}
)

func (x Dimension) Enum() *Dimension {
	p := new(Dimension)
	*p = x
	return p
}

func (x Dimension) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dimension) Descriptor() protoreflect.EnumDescriptor {
	return file_PositionAndVelocity_proto_enumTypes[0].Descriptor()
}

func (Dimension) Type() protoreflect.EnumType {
	return &file_PositionAndVelocity_proto_enumTypes[0]
}

func (x Dimension) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dimension.Descriptor instead.
func (Dimension) EnumDescriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{0}
}

// Note: All units are standardized. I.e: m/s, radian, meter
type GeodeticPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude *float32 `protobuf:"fixed32,1,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"` //radian
	Latitude  *float32 `protobuf:"fixed32,2,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`   //radian
	Altitude  *float32 `protobuf:"fixed32,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`   //meter
}

func (x *GeodeticPosition) Reset() {
	*x = GeodeticPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PositionAndVelocity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeodeticPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeodeticPosition) ProtoMessage() {}

func (x *GeodeticPosition) ProtoReflect() protoreflect.Message {
	mi := &file_PositionAndVelocity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeodeticPosition.ProtoReflect.Descriptor instead.
func (*GeodeticPosition) Descriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{0}
}

func (x *GeodeticPosition) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GeodeticPosition) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GeodeticPosition) GetAltitude() float32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

type CartesianPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float32 `protobuf:"fixed32,1,opt,name=x,proto3,oneof" json:"x,omitempty"` //meter
	Y *float32 `protobuf:"fixed32,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Z *float32 `protobuf:"fixed32,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
}

func (x *CartesianPosition) Reset() {
	*x = CartesianPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PositionAndVelocity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartesianPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartesianPosition) ProtoMessage() {}

func (x *CartesianPosition) ProtoReflect() protoreflect.Message {
	mi := &file_PositionAndVelocity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartesianPosition.ProtoReflect.Descriptor instead.
func (*CartesianPosition) Descriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{1}
}

func (x *CartesianPosition) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *CartesianPosition) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *CartesianPosition) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type PolarPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range     *float32 `protobuf:"fixed32,1,opt,name=range,proto3,oneof" json:"range,omitempty"`         //meter
	Azimuth   *float32 `protobuf:"fixed32,2,opt,name=azimuth,proto3,oneof" json:"azimuth,omitempty"`     //radian
	Elevation *float32 `protobuf:"fixed32,3,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"` //meter
}

func (x *PolarPosition) Reset() {
	*x = PolarPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PositionAndVelocity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolarPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarPosition) ProtoMessage() {}

func (x *PolarPosition) ProtoReflect() protoreflect.Message {
	mi := &file_PositionAndVelocity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarPosition.ProtoReflect.Descriptor instead.
func (*PolarPosition) Descriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{2}
}

func (x *PolarPosition) GetRange() float32 {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return 0
}

func (x *PolarPosition) GetAzimuth() float32 {
	if x != nil && x.Azimuth != nil {
		return *x.Azimuth
	}
	return 0
}

func (x *PolarPosition) GetElevation() float32 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

type CartesianVelocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vx *float32 `protobuf:"fixed32,1,opt,name=vx,proto3,oneof" json:"vx,omitempty"` //m/s
	Vy *float32 `protobuf:"fixed32,2,opt,name=vy,proto3,oneof" json:"vy,omitempty"`
	Vz *float32 `protobuf:"fixed32,3,opt,name=vz,proto3,oneof" json:"vz,omitempty"`
}

func (x *CartesianVelocity) Reset() {
	*x = CartesianVelocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PositionAndVelocity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartesianVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartesianVelocity) ProtoMessage() {}

func (x *CartesianVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_PositionAndVelocity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartesianVelocity.ProtoReflect.Descriptor instead.
func (*CartesianVelocity) Descriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{3}
}

func (x *CartesianVelocity) GetVx() float32 {
	if x != nil && x.Vx != nil {
		return *x.Vx
	}
	return 0
}

func (x *CartesianVelocity) GetVy() float32 {
	if x != nil && x.Vy != nil {
		return *x.Vy
	}
	return 0
}

func (x *CartesianVelocity) GetVz() float32 {
	if x != nil && x.Vz != nil {
		return *x.Vz
	}
	return 0
}

type PolarVelocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed   *float32 `protobuf:"fixed32,1,opt,name=speed,proto3,oneof" json:"speed,omitempty"`     //m/s
	Heading *float32 `protobuf:"fixed32,2,opt,name=heading,proto3,oneof" json:"heading,omitempty"` //radian
}

func (x *PolarVelocity) Reset() {
	*x = PolarVelocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PositionAndVelocity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolarVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolarVelocity) ProtoMessage() {}

func (x *PolarVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_PositionAndVelocity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolarVelocity.ProtoReflect.Descriptor instead.
func (*PolarVelocity) Descriptor() ([]byte, []int) {
	return file_PositionAndVelocity_proto_rawDescGZIP(), []int{4}
}

func (x *PolarVelocity) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *PolarVelocity) GetHeading() float32 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

var File_PositionAndVelocity_proto protoreflect.FileDescriptor

var file_PositionAndVelocity_proto_rawDesc = []byte{
	0x0a, 0x19, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x56, 0x65, 0x6c,
	0x6f, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x61, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x08,
	0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x61, 0x6c, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x5e, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x74, 0x65, 0x73, 0x69, 0x61, 0x6e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x01, 0x78, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x01, 0x7a, 0x88, 0x01,
	0x01, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x79, 0x42, 0x04, 0x0a,
	0x02, 0x5f, 0x7a, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x1d, 0x0a, 0x07, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x01, 0x52, 0x07, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x02, 0x52, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x6c, 0x65,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x74, 0x65, 0x73,
	0x69, 0x61, 0x6e, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x02, 0x76,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x02, 0x76, 0x78, 0x88, 0x01, 0x01,
	0x12, 0x13, 0x0a, 0x02, 0x76, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x02,
	0x76, 0x79, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x76, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x48, 0x02, 0x52, 0x02, 0x76, 0x7a, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x76,
	0x78, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x76, 0x79, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x76, 0x7a, 0x22,
	0x5f, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x19, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x00, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x2a, 0x2f, 0x0a, 0x09, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x0c, 0x44, 0x49, 0x4d, 0x45, 0x4e, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x32, 0x44, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x44, 0x49, 0x4d, 0x45, 0x4e, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x33, 0x44, 0x10,
	0x01, 0x42, 0x37, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x62, 0x6d, 0x73,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x18, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x5a, 0x05, 0x2e, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_PositionAndVelocity_proto_rawDescOnce sync.Once
	file_PositionAndVelocity_proto_rawDescData = file_PositionAndVelocity_proto_rawDesc
)

func file_PositionAndVelocity_proto_rawDescGZIP() []byte {
	file_PositionAndVelocity_proto_rawDescOnce.Do(func() {
		file_PositionAndVelocity_proto_rawDescData = protoimpl.X.CompressGZIP(file_PositionAndVelocity_proto_rawDescData)
	})
	return file_PositionAndVelocity_proto_rawDescData
}

var file_PositionAndVelocity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PositionAndVelocity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_PositionAndVelocity_proto_goTypes = []interface{}{
	(Dimension)(0),            // 0: com.vht.bms.messages.Dimension
	(*GeodeticPosition)(nil),  // 1: com.vht.bms.messages.GeodeticPosition
	(*CartesianPosition)(nil), // 2: com.vht.bms.messages.CartesianPosition
	(*PolarPosition)(nil),     // 3: com.vht.bms.messages.PolarPosition
	(*CartesianVelocity)(nil), // 4: com.vht.bms.messages.CartesianVelocity
	(*PolarVelocity)(nil),     // 5: com.vht.bms.messages.PolarVelocity
}
var file_PositionAndVelocity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PositionAndVelocity_proto_init() }
func file_PositionAndVelocity_proto_init() {
	if File_PositionAndVelocity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PositionAndVelocity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeodeticPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PositionAndVelocity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartesianPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PositionAndVelocity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolarPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PositionAndVelocity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartesianVelocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PositionAndVelocity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolarVelocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_PositionAndVelocity_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_PositionAndVelocity_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_PositionAndVelocity_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_PositionAndVelocity_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_PositionAndVelocity_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PositionAndVelocity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PositionAndVelocity_proto_goTypes,
		DependencyIndexes: file_PositionAndVelocity_proto_depIdxs,
		EnumInfos:         file_PositionAndVelocity_proto_enumTypes,
		MessageInfos:      file_PositionAndVelocity_proto_msgTypes,
	}.Build()
	File_PositionAndVelocity_proto = out.File
	file_PositionAndVelocity_proto_rawDesc = nil
	file_PositionAndVelocity_proto_goTypes = nil
	file_PositionAndVelocity_proto_depIdxs = nil
}
