// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: ipc/track/cmd/RemoveTrackCommand.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveTrackCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackIdList     []int32 `protobuf:"varint,1,rep,packed,name=track_id_list,json=trackIdList,proto3" json:"track_id_list,omitempty"`
	RemoveAllTracks bool    `protobuf:"varint,2,opt,name=remove_all_tracks,json=removeAllTracks,proto3" json:"remove_all_tracks,omitempty"` // If true, request to remove all tracks regardless track id list content
}

func (x *RemoveTrackCommand) Reset() {
	*x = RemoveTrackCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipc_track_cmd_RemoveTrackCommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTrackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrackCommand) ProtoMessage() {}

func (x *RemoveTrackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ipc_track_cmd_RemoveTrackCommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrackCommand.ProtoReflect.Descriptor instead.
func (*RemoveTrackCommand) Descriptor() ([]byte, []int) {
	return file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveTrackCommand) GetTrackIdList() []int32 {
	if x != nil {
		return x.TrackIdList
	}
	return nil
}

func (x *RemoveTrackCommand) GetRemoveAllTracks() bool {
	if x != nil {
		return x.RemoveAllTracks
	}
	return false
}

var File_ipc_track_cmd_RemoveTrackCommand_proto protoreflect.FileDescriptor

var file_ipc_track_cmd_RemoveTrackCommand_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6d, 0x64, 0x2f,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68,
	0x74, 0x2e, 0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x64,
	0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x73, 0x42, 0x40, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e,
	0x62, 0x6d, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x42, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a,
	0x05, 0x2e, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescOnce sync.Once
	file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescData = file_ipc_track_cmd_RemoveTrackCommand_proto_rawDesc
)

func file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescGZIP() []byte {
	file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescOnce.Do(func() {
		file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescData)
	})
	return file_ipc_track_cmd_RemoveTrackCommand_proto_rawDescData
}

var file_ipc_track_cmd_RemoveTrackCommand_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ipc_track_cmd_RemoveTrackCommand_proto_goTypes = []interface{}{
	(*RemoveTrackCommand)(nil), // 0: com.vht.bms.messages.RemoveTrackCommand
}
var file_ipc_track_cmd_RemoveTrackCommand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipc_track_cmd_RemoveTrackCommand_proto_init() }
func file_ipc_track_cmd_RemoveTrackCommand_proto_init() {
	if File_ipc_track_cmd_RemoveTrackCommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipc_track_cmd_RemoveTrackCommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTrackCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipc_track_cmd_RemoveTrackCommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipc_track_cmd_RemoveTrackCommand_proto_goTypes,
		DependencyIndexes: file_ipc_track_cmd_RemoveTrackCommand_proto_depIdxs,
		MessageInfos:      file_ipc_track_cmd_RemoveTrackCommand_proto_msgTypes,
	}.Build()
	File_ipc_track_cmd_RemoveTrackCommand_proto = out.File
	file_ipc_track_cmd_RemoveTrackCommand_proto_rawDesc = nil
	file_ipc_track_cmd_RemoveTrackCommand_proto_goTypes = nil
	file_ipc_track_cmd_RemoveTrackCommand_proto_depIdxs = nil
}
