// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orders": {
            "get": {
                "description": "Find all order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Find all order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a order",
                "parameters": [
                    {
                        "description": "order body",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.CreateOrderRequest"
                        }
                    },
                    {
                        "type": "boolean",
                        "description": "event api call flag",
                        "name": "eventAPI",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/search": {
            "get": {
                "description": "Search order use Query option https://github.com/jtlabsio/mongo/",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Search order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number",
                        "name": "page[page]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page[size]",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "filter by isDemo (true/false)",
                        "name": "filter[is_demo]",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.Order"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/searchStatus": {
            "get": {
                "description": "Search order by status using Query option https://github.com/jtlabsio/mongo/",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Search order by status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "order status",
                        "name": "filter[order_status]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number (0-based)",
                        "name": "page[page]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page[size]",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "description": "Find order by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Find order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update order by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Update order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "order body",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pb.Order"
                        }
                    },
                    {
                        "type": "boolean",
                        "description": "event api call flag",
                        "name": "eventAPI",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.Order"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete order by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Delete order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "event api call flag",
                        "name": "eventAPI",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.Order"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch order by ID use standard of JSON PATCH https://jsonpatch.com/",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Patch order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch operation format Array of Operation Add, Remove, Replace, Copy, Move, Test. Get example at https://jsonpatch.com/",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jsonpatch.Operation"
                            }
                        }
                    },
                    {
                        "type": "boolean",
                        "description": "event api call flag",
                        "name": "eventAPI",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pb.PatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/orders": {
            "get": {
                "description": "**Kết nối**\n- Endpoint: ` + "`" + `GET /ws/orders` + "`" + `\n- Server trả về HTTP ` + "`" + `101 Switching Protocols` + "`" + ` và nâng cấp kết nối lên WebSocket.\n- Sau khi kết nối, mọi bản tin sẽ được gửi qua WebSocket, **không** phải response HTTP thông thường.\n\n**Khi nào server gửi bản tin**\n- Chỉ gửi cho các **đơn demo** (` + "`" + `is_demo = true` + "`" + `).\n- Khi **tạo mới** đơn demo (sau khi tạo flight notification thành công) ⇒ ` + "`" + `action = \"create\"` + "`" + `.\n- Khi **cập nhật** đơn demo qua API PATCH ⇒ ` + "`" + `action = \"update\"` + "`" + `.\n\n**Format bản tin WebSocket**\nBản tin luôn có dạng:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"action\": \"create\",            // hoặc \"update\"\n\"data\": {\n\"id\": \"7175489d-5019-46bc-b5ad-d36b1e3e0899\",\n\"int_id\": 61410,\n\"source\": \"693673e2bbb6e622e589b03e\",\n\"dest\": \"693673e2bbb6e622e589b03d\",\n\"order_status\": 2,           // 1=PENDING, 2=IN_DELIVERY, 3=DELIVERED, 4=CANCELED\n\"drone_id\": \"VT02\",\n\"gcs_id\": \"\",\n\"segments\": [],\n\"user_create_id\": \"TrongVQ\",\n\"weight\": 1,\n\"size\": 1,\n\"priority\": 1,\n\"time_window\": {\n\"start_time\": 0,\n\"end_time\": 0\n},\n\"corridor_id\": \"\",\n\"eta\": 1765861561000,        // millis, thời gian dự kiến kết thúc bay\n\"is_demo\": true,\n\"flight_notification_id\": \"fn-abc\",\n\"flight_notification_name\": \"Approval ...\",\n\"flight_authorization_approval_id\": \"approval-id\",\n\"flight_notification_status\": \"ACTIVATED\",\n\"created_at\": 1765860661000,\n\"updated_at\": 1765860761000,\n\"created_by\": \"\",\n\"updated_by\": \"\"\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\nTrong đó:\n- ` + "`" + `action` + "`" + `: ` + "`" + `\"create\"` + "`" + ` hoặc ` + "`" + `\"update\"` + "`" + ` để FE biết là tạo mới hay cập nhật.\n- ` + "`" + `data` + "`" + `: chính là ` + "`" + `OrderResponse` + "`" + ` (schema giống với các API ` + "`" + `/orders` + "`" + ` khác).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "WebSocket connection for order notifications",
                "responses": {
                    "101": {
                        "description": "WebSocket connection established. Messages are sent in format: { \\\"action\\\": \\\"create\\\"|\\\"update\\\", \\\"data\\\": OrderResponse }",
                        "schema": {
                            "$ref": "#/definitions/order.WebSocketOrderMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jsonpatch.Operation": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "integer"
                }
            }
        },
        "order.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "corridor_id": {
                    "type": "string"
                },
                "dest": {
                    "description": "điểm đích",
                    "type": "string"
                },
                "drone_id": {
                    "type": "string"
                },
                "eta": {
                    "type": "integer"
                },
                "gcs_id": {
                    "type": "string"
                },
                "is_demo": {
                    "description": "đơn hàng demo hay đơn hàng thật",
                    "type": "boolean"
                },
                "order_status": {
                    "description": "map sang pb.AT_ORDER_STATUS nếu cần",
                    "type": "integer"
                },
                "priority": {
                    "description": "map sang pb.AT_ORDER_PRORITY",
                    "type": "integer"
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/order.SegmentRequest"
                    }
                },
                "size": {
                    "description": "map sang pb.AT_ORDER_SIZE",
                    "type": "integer"
                },
                "source": {
                    "description": "điểm xuất phát",
                    "type": "string"
                },
                "time_window": {
                    "$ref": "#/definitions/order.TimeWindowRequest"
                },
                "user_create_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "order.OrderResponse": {
            "type": "object",
            "properties": {
                "corridor_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "type": "string"
                },
                "dest": {
                    "description": "điểm đích",
                    "type": "string"
                },
                "drone_id": {
                    "type": "string"
                },
                "eta": {
                    "type": "integer"
                },
                "flight_authorization_approval_id": {
                    "type": "string"
                },
                "flight_notification_id": {
                    "description": "Flight notification fields (từ response của API /flight-notifications)",
                    "type": "string"
                },
                "flight_notification_name": {
                    "type": "string"
                },
                "flight_notification_status": {
                    "type": "string"
                },
                "gcs_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "int_id": {
                    "description": "mã đơn dạng số nguyên 5 chữ số",
                    "type": "integer"
                },
                "is_demo": {
                    "description": "đơn hàng demo hay đơn hàng thật",
                    "type": "boolean"
                },
                "order_status": {
                    "description": "map sang pb.AT_ORDER_STATUS nếu cần",
                    "type": "integer"
                },
                "priority": {
                    "description": "map sang pb.AT_ORDER_PRORITY",
                    "type": "integer"
                },
                "segments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/order.SegmentRequest"
                    }
                },
                "size": {
                    "description": "map sang pb.AT_ORDER_SIZE",
                    "type": "integer"
                },
                "source": {
                    "description": "điểm xuất phát",
                    "type": "string"
                },
                "time_window": {
                    "$ref": "#/definitions/order.TimeWindowRequest"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                },
                "user_create_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "order.SegmentRequest": {
            "type": "object",
            "properties": {
                "dest": {
                    "type": "string"
                },
                "drone_id": {
                    "type": "string"
                },
                "flight_lane_id": {
                    "type": "string"
                },
                "segment_index": {
                    "type": "integer"
                },
                "segment_status": {
                    "description": "map sang pb.AT_SEGMENT_STATUS",
                    "type": "integer"
                },
                "segment_type": {
                    "description": "map sang pb.AT_SEGMENT_TYPE",
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "order.TimeWindowRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "order.WebSocketOrderMessage": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action của sự kiện.\n- create: tạo mới đơn (sau khi tạo flight notification thành công)\n- update: cập nhật đơn (PATCH)\n\nenum: create,update",
                    "type": "string",
                    "example": "create"
                },
                "data": {
                    "description": "Data là payload chi tiết của order sau khi tạo/cập nhật.\nSchema giống như OrderResponse đang dùng cho HTTP API.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/order.OrderResponse"
                        }
                    ]
                }
            }
        },
        "pb.AT_ORDER_PRORITY": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "AT_ORDER_PRORITY_AOP_UKNOWN",
                "AT_ORDER_PRORITY_AOP_NORMAL",
                "AT_ORDER_PRORITY_AOP_HIGH"
            ]
        },
        "pb.AT_ORDER_SIZE": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "AT_ORDER_SIZE_AOSZ_UNKNOWN",
                "AT_ORDER_SIZE_AOSZ_SMALL",
                "AT_ORDER_SIZE_AOSZ_MEDIUM",
                "AT_ORDER_SIZE_AOSZ_LARGE",
                "AT_ORDER_SIZE_AOSZ_OVERSIZE"
            ]
        },
        "pb.AT_ORDER_STATUS": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "AT_ORDER_STATUS_AOS_UNKNOWN",
                "AT_ORDER_STATUS_AOS_PENDING",
                "AT_ORDER_STATUS_AOS_IN_DELIVERY",
                "AT_ORDER_STATUS_AOS_DELIVERED",
                "AT_ORDER_STATUS_AOS_CANCELED"
            ]
        },
        "pb.AT_SEGMENT_STATUS": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "AT_SEGMENT_STATUS_ASS_UKNOWN",
                "AT_SEGMENT_STATUS_ASS_UNFINISHED",
                "AT_SEGMENT_STATUS_ASS_FINISHED"
            ]
        },
        "pb.AT_SEGMENT_TYPE": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "AT_SEGMENT_TYPE_AST_UKNOWN",
                "AT_SEGMENT_TYPE_AST_PRE_DELIVERY_ROUTE",
                "AT_SEGMENT_TYPE_AST_IN_DELIVERY_ROUTE",
                "AT_SEGMENT_TYPE_AST_RETURN_FLIGHT_ROUTE"
            ]
        },
        "pb.Order": {
            "type": "object",
            "properties": {
                "corridor_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "created_by": {
                    "type": "string"
                },
                "dest": {
                    "type": "string"
                },
                "drone_id": {
                    "type": "string"
                },
                "eta": {
                    "type": "integer"
                },
                "gcs_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_status": {
                    "$ref": "#/definitions/pb.AT_ORDER_STATUS"
                },
                "priority": {
                    "$ref": "#/definitions/pb.AT_ORDER_PRORITY"
                },
                "segments": {
                    "description": "repeated spatial_attribute.GeodeticPositionWithTime FlightRoute  = 7;//` + "`" + `json:\"flight_route,omitempty\" bson:\"flight_route\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pb.Segments"
                    }
                },
                "size": {
                    "$ref": "#/definitions/pb.AT_ORDER_SIZE"
                },
                "source": {
                    "type": "string"
                },
                "time_window": {
                    "$ref": "#/definitions/pb.TimeWindow"
                },
                "updated_at": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                },
                "user_create_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "pb.PatchResponse": {
            "type": "object",
            "properties": {
                "IsOk": {
                    "type": "boolean"
                },
                "Message": {
                    "type": "string"
                }
            }
        },
        "pb.Segments": {
            "type": "object",
            "properties": {
                "dest": {
                    "type": "string"
                },
                "drone_id": {
                    "type": "string"
                },
                "flight_lane_id": {
                    "type": "string"
                },
                "segment_index": {
                    "type": "integer"
                },
                "segment_status": {
                    "$ref": "#/definitions/pb.AT_SEGMENT_STATUS"
                },
                "segment_type": {
                    "$ref": "#/definitions/pb.AT_SEGMENT_TYPE"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "pb.TimeWindow": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "types.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Go Template Project API",
	Description:      "This is a sample Go Template server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
