// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/Track.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kieu loai quy dao
type AIRCRAFT_TYPE int32

const (
	// FROM VQ
	AIRCRAFT_TYPE_AT_UNKNOWN           AIRCRAFT_TYPE = 0  // CXD
	AIRCRAFT_TYPE_AT_BOMBER            AIRCRAFT_TYPE = 1  // May bay nem bom
	AIRCRAFT_TYPE_AT_HELICOPTER        AIRCRAFT_TYPE = 2  // Truc thang
	AIRCRAFT_TYPE_AT_TRANSPORT         AIRCRAFT_TYPE = 3  // Van tai
	AIRCRAFT_TYPE_AT_REFUEL            AIRCRAFT_TYPE = 4  // Tiep dau
	AIRCRAFT_TYPE_AT_RECONNAISSANCE    AIRCRAFT_TYPE = 5  // Trinh sat
	AIRCRAFT_TYPE_AT_ECM               AIRCRAFT_TYPE = 6  // Tac chien dien tu
	AIRCRAFT_TYPE_AT_AWACS             AIRCRAFT_TYPE = 7  // Chi huy tren khong
	AIRCRAFT_TYPE_AT_TRAINING          AIRCRAFT_TYPE = 8  // Huan luyen
	AIRCRAFT_TYPE_AT_STRATEGIC_BOMBER  AIRCRAFT_TYPE = 9  // Nem bom chien luoc
	AIRCRAFT_TYPE_AT_CRUISE_MISSILE    AIRCRAFT_TYPE = 10 // Ten lua hanh trinh
	AIRCRAFT_TYPE_AT_BALLISTIC_MISSILE AIRCRAFT_TYPE = 11 // Ten lua dan dao
	AIRCRAFT_TYPE_AT_UAV               AIRCRAFT_TYPE = 12 // UAV chung dung cho ca VQC-PK, neu chua xac dinh canh quat, canh bang
	AIRCRAFT_TYPE_AT_AEROSTAT          AIRCRAFT_TYPE = 13 // Khinh khi cau
	AIRCRAFT_TYPE_AT_CIVIL             AIRCRAFT_TYPE = 14 // HKDD
	AIRCRAFT_TYPE_AT_FIGHTER           AIRCRAFT_TYPE = 15 // Chien dau
	//For VQC-PK
	AIRCRAFT_TYPE_AT_DRONE      AIRCRAFT_TYPE = 16 // Drone - UAV canh quat
	AIRCRAFT_TYPE_AT_FIXED_WING AIRCRAFT_TYPE = 17 // UAV canh bang
	AIRCRAFT_TYPE_AT_BOMB       AIRCRAFT_TYPE = 18 // Bom
)

// Enum value maps for AIRCRAFT_TYPE.
var (
	AIRCRAFT_TYPE_name = map[int32]string{
		0:  "AT_UNKNOWN",
		1:  "AT_BOMBER",
		2:  "AT_HELICOPTER",
		3:  "AT_TRANSPORT",
		4:  "AT_REFUEL",
		5:  "AT_RECONNAISSANCE",
		6:  "AT_ECM",
		7:  "AT_AWACS",
		8:  "AT_TRAINING",
		9:  "AT_STRATEGIC_BOMBER",
		10: "AT_CRUISE_MISSILE",
		11: "AT_BALLISTIC_MISSILE",
		12: "AT_UAV",
		13: "AT_AEROSTAT",
		14: "AT_CIVIL",
		15: "AT_FIGHTER",
		16: "AT_DRONE",
		17: "AT_FIXED_WING",
		18: "AT_BOMB",
	}
	AIRCRAFT_TYPE_value = map[string]int32{
		"AT_UNKNOWN":           0,
		"AT_BOMBER":            1,
		"AT_HELICOPTER":        2,
		"AT_TRANSPORT":         3,
		"AT_REFUEL":            4,
		"AT_RECONNAISSANCE":    5,
		"AT_ECM":               6,
		"AT_AWACS":             7,
		"AT_TRAINING":          8,
		"AT_STRATEGIC_BOMBER":  9,
		"AT_CRUISE_MISSILE":    10,
		"AT_BALLISTIC_MISSILE": 11,
		"AT_UAV":               12,
		"AT_AEROSTAT":          13,
		"AT_CIVIL":             14,
		"AT_FIGHTER":           15,
		"AT_DRONE":             16,
		"AT_FIXED_WING":        17,
		"AT_BOMB":              18,
	}
)

func (x AIRCRAFT_TYPE) Enum() *AIRCRAFT_TYPE {
	p := new(AIRCRAFT_TYPE)
	*p = x
	return p
}

func (x AIRCRAFT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AIRCRAFT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Track_proto_enumTypes[0].Descriptor()
}

func (AIRCRAFT_TYPE) Type() protoreflect.EnumType {
	return &file_pkg_proto_Track_proto_enumTypes[0]
}

func (x AIRCRAFT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AIRCRAFT_TYPE.Descriptor instead.
func (AIRCRAFT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{0}
}

// Nhan dang
/// Xem xet lai so luong nhan dang, co nhan quy dao tu VQ ko ???
type TRACK_IDENTIFICATION int32

const (
	TRACK_IDENTIFICATION_TI_UNKNOWN       TRACK_IDENTIFICATION = 0 // Chua xac dinh
	TRACK_IDENTIFICATION_TI_DOMESTIC      TRACK_IDENTIFICATION = 1 // Quan su
	TRACK_IDENTIFICATION_TI_HOSTILE       TRACK_IDENTIFICATION = 2 // Dich
	TRACK_IDENTIFICATION_TI_ALLY          TRACK_IDENTIFICATION = 3 // Quoc noi
	TRACK_IDENTIFICATION_TI_INTERNATIONAL TRACK_IDENTIFICATION = 4 // Quoc te
	TRACK_IDENTIFICATION_TI_OVERFLIGHT    TRACK_IDENTIFICATION = 5 // Qua canh
)

// Enum value maps for TRACK_IDENTIFICATION.
var (
	TRACK_IDENTIFICATION_name = map[int32]string{
		0: "TI_UNKNOWN",
		1: "TI_DOMESTIC",
		2: "TI_HOSTILE",
		3: "TI_ALLY",
		4: "TI_INTERNATIONAL",
		5: "TI_OVERFLIGHT",
	}
	TRACK_IDENTIFICATION_value = map[string]int32{
		"TI_UNKNOWN":       0,
		"TI_DOMESTIC":      1,
		"TI_HOSTILE":       2,
		"TI_ALLY":          3,
		"TI_INTERNATIONAL": 4,
		"TI_OVERFLIGHT":    5,
	}
)

func (x TRACK_IDENTIFICATION) Enum() *TRACK_IDENTIFICATION {
	p := new(TRACK_IDENTIFICATION)
	*p = x
	return p
}

func (x TRACK_IDENTIFICATION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TRACK_IDENTIFICATION) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Track_proto_enumTypes[1].Descriptor()
}

func (TRACK_IDENTIFICATION) Type() protoreflect.EnumType {
	return &file_pkg_proto_Track_proto_enumTypes[1]
}

func (x TRACK_IDENTIFICATION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TRACK_IDENTIFICATION.Descriptor instead.
func (TRACK_IDENTIFICATION) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{1}
}

// Canh bao
/// Xem muc tieu (thuoc TI_UNKNOWN hoac TI_HOSTILE) co nam trong vung Canh bao hoac vung Bao ve ko??
type TRACK_ALERT int32

const (
	TRACK_ALERT_TA_UNKNOWN TRACK_ALERT = 0 // Khong canh bao
	TRACK_ALERT_TA_WARNING TRACK_ALERT = 1 // Nam giua vung bao ve va vung canh bao
	TRACK_ALERT_TA_DANGER  TRACK_ALERT = 2 // Nam trong vung bao ve
)

// Enum value maps for TRACK_ALERT.
var (
	TRACK_ALERT_name = map[int32]string{
		0: "TA_UNKNOWN",
		1: "TA_WARNING",
		2: "TA_DANGER",
	}
	TRACK_ALERT_value = map[string]int32{
		"TA_UNKNOWN": 0,
		"TA_WARNING": 1,
		"TA_DANGER":  2,
	}
)

func (x TRACK_ALERT) Enum() *TRACK_ALERT {
	p := new(TRACK_ALERT)
	*p = x
	return p
}

func (x TRACK_ALERT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TRACK_ALERT) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_Track_proto_enumTypes[2].Descriptor()
}

func (TRACK_ALERT) Type() protoreflect.EnumType {
	return &file_pkg_proto_Track_proto_enumTypes[2]
}

func (x TRACK_ALERT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TRACK_ALERT.Descriptor instead.
func (TRACK_ALERT) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{2}
}

////////================================================================================
//1. Thông tin qũy đạo
type Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             int32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                                                               // Track ID
	TrackNumber    int32                 `protobuf:"varint,2,opt,name=TrackNumber,proto3" json:"TrackNumber,omitempty"`                                             // Track Number
	Altitude       float32               `protobuf:"fixed32,3,opt,name=Altitude,proto3" json:"Altitude,omitempty"`                                                  // Do cao
	Latitude       float32               `protobuf:"fixed32,4,opt,name=Latitude,proto3" json:"Latitude,omitempty"`                                                  // Kinh do
	Longitude      float32               `protobuf:"fixed32,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`                                                // Vi do
	AircraftType   *AIRCRAFT_TYPE        `protobuf:"varint,6,opt,name=AircraftType,proto3,enum=track.AIRCRAFT_TYPE,oneof" json:"AircraftType,omitempty"`            // Kieu loai quy dao
	Identification *TRACK_IDENTIFICATION `protobuf:"varint,7,opt,name=Identification,proto3,enum=track.TRACK_IDENTIFICATION,oneof" json:"Identification,omitempty"` // Nhan dang
	Quantity       int32                 `protobuf:"varint,8,opt,name=Quantity,proto3" json:"Quantity,omitempty"`                                                   // So luong
	Model          string                `protobuf:"bytes,9,opt,name=Model,proto3" json:"Model,omitempty"`                                                          // Model cua quy dao, vd: M96, Shahed...
	Velocity       float32               `protobuf:"fixed32,10,opt,name=Velocity,proto3" json:"Velocity,omitempty"`                                                 // Van toc
	Heading        float32               `protobuf:"fixed32,11,opt,name=Heading,proto3" json:"Heading,omitempty"`                                                   // Huong
	Quality        int32                 `protobuf:"varint,12,opt,name=Quality,proto3" json:"Quality,omitempty"`                                                    // Chat luong
	ListSources    []*TrackSourceInfo    `protobuf:"bytes,13,rep,name=ListSources,proto3" json:"ListSources,omitempty"`                                             // Danh sach Nguon
	PrimarySource  *TrackSourceInfo      `protobuf:"bytes,14,opt,name=PrimarySource,proto3" json:"PrimarySource,omitempty"`                                         // Nguon hien tai - noi tong hop hien tai (hay nguon chinh ???)
	Mode3A         string                `protobuf:"bytes,15,opt,name=Mode3a,proto3" json:"Mode3a,omitempty"`                                                       // Ma 3A
	Serial         string                `protobuf:"bytes,16,opt,name=Serial,proto3" json:"Serial,omitempty"`                                                       // Serial
	Shape          string                `protobuf:"bytes,17,opt,name=Shape,proto3" json:"Shape,omitempty"`                                                         // 0: canh bang, 1: cach quat, 2: Khong xac dinh
	Alert          *TRACK_ALERT          `protobuf:"varint,18,opt,name=Alert,proto3,enum=track.TRACK_ALERT,oneof" json:"Alert,omitempty"`                           // 0: binh thuong, 1: nam trong vung canh bao, 2: nam trong vung bao ve
	CreatedAt      int64                 `protobuf:"varint,100,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                                               // Thoi gian tao
	UpdatedAt      int64                 `protobuf:"varint,101,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                                               // Thoi gian cap nhat
}

func (x *Track) Reset() {
	*x = Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_Track_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Track_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Track) GetTrackNumber() int32 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

func (x *Track) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Track) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Track) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Track) GetAircraftType() AIRCRAFT_TYPE {
	if x != nil && x.AircraftType != nil {
		return *x.AircraftType
	}
	return AIRCRAFT_TYPE_AT_UNKNOWN
}

func (x *Track) GetIdentification() TRACK_IDENTIFICATION {
	if x != nil && x.Identification != nil {
		return *x.Identification
	}
	return TRACK_IDENTIFICATION_TI_UNKNOWN
}

func (x *Track) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Track) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Track) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *Track) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Track) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Track) GetListSources() []*TrackSourceInfo {
	if x != nil {
		return x.ListSources
	}
	return nil
}

func (x *Track) GetPrimarySource() *TrackSourceInfo {
	if x != nil {
		return x.PrimarySource
	}
	return nil
}

func (x *Track) GetMode3A() string {
	if x != nil {
		return x.Mode3A
	}
	return ""
}

func (x *Track) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Track) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Track) GetAlert() TRACK_ALERT {
	if x != nil && x.Alert != nil {
		return *x.Alert
	}
	return TRACK_ALERT_TA_UNKNOWN
}

func (x *Track) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Track) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Thong tin nguon quy dao
type TrackSourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceName  string `protobuf:"bytes,1,opt,name=SourceName,proto3" json:"SourceName,omitempty"`   // Ten nguon phat hien
	TrackNumber string `protobuf:"bytes,2,opt,name=TrackNumber,proto3" json:"TrackNumber,omitempty"` // So hieu local cua quy dao theo nguon do
}

func (x *TrackSourceInfo) Reset() {
	*x = TrackSourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_Track_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSourceInfo) ProtoMessage() {}

func (x *TrackSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Track_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSourceInfo.ProtoReflect.Descriptor instead.
func (*TrackSourceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{1}
}

func (x *TrackSourceInfo) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *TrackSourceInfo) GetTrackNumber() string {
	if x != nil {
		return x.TrackNumber
	}
	return ""
}

////////================================================================================
//2. Ban tin xoa quy dao
type DeleteTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=TrackId,proto3" json:"TrackId,omitempty"`
}

func (x *DeleteTrack) Reset() {
	*x = DeleteTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_Track_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrack) ProtoMessage() {}

func (x *DeleteTrack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Track_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTrack.ProtoReflect.Descriptor instead.
func (*DeleteTrack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTrack) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

////////================================================================================
//3. Ban tin chua id cua cac quy dao hien tai
type ListCurrentTracks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId []int32 `protobuf:"varint,1,rep,packed,name=TrackId,proto3" json:"TrackId,omitempty"`
}

func (x *ListCurrentTracks) Reset() {
	*x = ListCurrentTracks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_Track_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCurrentTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrentTracks) ProtoMessage() {}

func (x *ListCurrentTracks) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_Track_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrentTracks.ProtoReflect.Descriptor instead.
func (*ListCurrentTracks) Descriptor() ([]byte, []int) {
	return file_pkg_proto_Track_proto_rawDescGZIP(), []int{3}
}

func (x *ListCurrentTracks) GetTrackId() []int32 {
	if x != nil {
		return x.TrackId
	}
	return nil
}

var File_pkg_proto_Track_proto protoreflect.FileDescriptor

var file_pkg_proto_Track_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0xf1,
	0x05, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x41, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x3d, 0x0a, 0x0c, 0x41, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x41,
	0x49, 0x52, 0x43, 0x52, 0x41, 0x46, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x48, 0x00, 0x52, 0x0c,
	0x41, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x48, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e,
	0x54, 0x52, 0x41, 0x43, 0x4b, 0x5f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x48, 0x01, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x56,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x56,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x65, 0x33, 0x61, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x65, 0x33, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x2e, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x48, 0x02, 0x52, 0x05,
	0x41, 0x6c, 0x65, 0x72, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x41, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x22, 0x53, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x22, 0x2d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x2a,
	0xd7, 0x02, 0x0a, 0x0d, 0x41, 0x49, 0x52, 0x43, 0x52, 0x41, 0x46, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x54, 0x5f, 0x42, 0x4f, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x41, 0x54, 0x5f, 0x48, 0x45, 0x4c, 0x49, 0x43, 0x4f, 0x50, 0x54, 0x45,
	0x52, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50,
	0x4f, 0x52, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x46, 0x55,
	0x45, 0x4c, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4e,
	0x4e, 0x41, 0x49, 0x53, 0x53, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x54, 0x5f, 0x45, 0x43, 0x4d, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x54, 0x5f, 0x41, 0x57,
	0x41, 0x43, 0x53, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x49,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x54, 0x5f, 0x53, 0x54, 0x52,
	0x41, 0x54, 0x45, 0x47, 0x49, 0x43, 0x5f, 0x42, 0x4f, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x09, 0x12,
	0x15, 0x0a, 0x11, 0x41, 0x54, 0x5f, 0x43, 0x52, 0x55, 0x49, 0x53, 0x45, 0x5f, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4c, 0x45, 0x10, 0x0a, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x54, 0x5f, 0x42, 0x41, 0x4c,
	0x4c, 0x49, 0x53, 0x54, 0x49, 0x43, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4c, 0x45, 0x10, 0x0b,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x54, 0x5f, 0x55, 0x41, 0x56, 0x10, 0x0c, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x54, 0x5f, 0x41, 0x45, 0x52, 0x4f, 0x53, 0x54, 0x41, 0x54, 0x10, 0x0d, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x54, 0x5f, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x10, 0x0e, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x54, 0x5f, 0x46, 0x49, 0x47, 0x48, 0x54, 0x45, 0x52, 0x10, 0x0f, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x54, 0x5f, 0x44, 0x52, 0x4f, 0x4e, 0x45, 0x10, 0x10, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x54, 0x5f,
	0x46, 0x49, 0x58, 0x45, 0x44, 0x5f, 0x57, 0x49, 0x4e, 0x47, 0x10, 0x11, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x54, 0x5f, 0x42, 0x4f, 0x4d, 0x42, 0x10, 0x12, 0x2a, 0x7d, 0x0a, 0x14, 0x54, 0x52, 0x41,
	0x43, 0x4b, 0x5f, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x49, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x49, 0x5f, 0x44, 0x4f, 0x4d, 0x45, 0x53, 0x54, 0x49, 0x43,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x49, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x49, 0x4c, 0x45,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x5f, 0x41, 0x4c, 0x4c, 0x59, 0x10, 0x03, 0x12,
	0x14, 0x0a, 0x10, 0x54, 0x49, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x49, 0x5f, 0x4f, 0x56, 0x45, 0x52,
	0x46, 0x4c, 0x49, 0x47, 0x48, 0x54, 0x10, 0x05, 0x2a, 0x3c, 0x0a, 0x0b, 0x54, 0x52, 0x41, 0x43,
	0x4b, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x41, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x41, 0x5f, 0x57, 0x41,
	0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x41, 0x5f, 0x44, 0x41,
	0x4e, 0x47, 0x45, 0x52, 0x10, 0x02, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_Track_proto_rawDescOnce sync.Once
	file_pkg_proto_Track_proto_rawDescData = file_pkg_proto_Track_proto_rawDesc
)

func file_pkg_proto_Track_proto_rawDescGZIP() []byte {
	file_pkg_proto_Track_proto_rawDescOnce.Do(func() {
		file_pkg_proto_Track_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_Track_proto_rawDescData)
	})
	return file_pkg_proto_Track_proto_rawDescData
}

var file_pkg_proto_Track_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_Track_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_Track_proto_goTypes = []interface{}{
	(AIRCRAFT_TYPE)(0),        // 0: track.AIRCRAFT_TYPE
	(TRACK_IDENTIFICATION)(0), // 1: track.TRACK_IDENTIFICATION
	(TRACK_ALERT)(0),          // 2: track.TRACK_ALERT
	(*Track)(nil),             // 3: track.Track
	(*TrackSourceInfo)(nil),   // 4: track.TrackSourceInfo
	(*DeleteTrack)(nil),       // 5: track.DeleteTrack
	(*ListCurrentTracks)(nil), // 6: track.ListCurrentTracks
}
var file_pkg_proto_Track_proto_depIdxs = []int32{
	0, // 0: track.Track.AircraftType:type_name -> track.AIRCRAFT_TYPE
	1, // 1: track.Track.Identification:type_name -> track.TRACK_IDENTIFICATION
	4, // 2: track.Track.ListSources:type_name -> track.TrackSourceInfo
	4, // 3: track.Track.PrimarySource:type_name -> track.TrackSourceInfo
	2, // 4: track.Track.Alert:type_name -> track.TRACK_ALERT
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_Track_proto_init() }
func file_pkg_proto_Track_proto_init() {
	if File_pkg_proto_Track_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_Track_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_Track_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackSourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_Track_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_Track_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCurrentTracks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_Track_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_Track_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_Track_proto_goTypes,
		DependencyIndexes: file_pkg_proto_Track_proto_depIdxs,
		EnumInfos:         file_pkg_proto_Track_proto_enumTypes,
		MessageInfos:      file_pkg_proto_Track_proto_msgTypes,
	}.Build()
	File_pkg_proto_Track_proto = out.File
	file_pkg_proto_Track_proto_rawDesc = nil
	file_pkg_proto_Track_proto_goTypes = nil
	file_pkg_proto_Track_proto_depIdxs = nil
}
