// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/ag_algo/AfAlertService.proto

package ag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AfAlertService_CalculateAlert_FullMethodName = "/com.vht.afad.afmessages.AfAlertService/CalculateAlert"
)

// AfAlertServiceClient is the client API for AfAlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AfAlertServiceClient interface {
	CalculateAlert(ctx context.Context, in *AfAlertRequest, opts ...grpc.CallOption) (*GRPCFlightList, error)
}

type afAlertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAfAlertServiceClient(cc grpc.ClientConnInterface) AfAlertServiceClient {
	return &afAlertServiceClient{cc}
}

func (c *afAlertServiceClient) CalculateAlert(ctx context.Context, in *AfAlertRequest, opts ...grpc.CallOption) (*GRPCFlightList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightList)
	err := c.cc.Invoke(ctx, AfAlertService_CalculateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AfAlertServiceServer is the server API for AfAlertService service.
// All implementations must embed UnimplementedAfAlertServiceServer
// for forward compatibility.
type AfAlertServiceServer interface {
	CalculateAlert(context.Context, *AfAlertRequest) (*GRPCFlightList, error)
	mustEmbedUnimplementedAfAlertServiceServer()
}

// UnimplementedAfAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAfAlertServiceServer struct{}

func (UnimplementedAfAlertServiceServer) CalculateAlert(context.Context, *AfAlertRequest) (*GRPCFlightList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateAlert not implemented")
}
func (UnimplementedAfAlertServiceServer) mustEmbedUnimplementedAfAlertServiceServer() {}
func (UnimplementedAfAlertServiceServer) testEmbeddedByValue()                        {}

// UnsafeAfAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfAlertServiceServer will
// result in compilation errors.
type UnsafeAfAlertServiceServer interface {
	mustEmbedUnimplementedAfAlertServiceServer()
}

func RegisterAfAlertServiceServer(s grpc.ServiceRegistrar, srv AfAlertServiceServer) {
	// If the following call pancis, it indicates UnimplementedAfAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AfAlertService_ServiceDesc, srv)
}

func _AfAlertService_CalculateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfAlertServiceServer).CalculateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfAlertService_CalculateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfAlertServiceServer).CalculateAlert(ctx, req.(*AfAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AfAlertService_ServiceDesc is the grpc.ServiceDesc for AfAlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AfAlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.vht.afad.afmessages.AfAlertService",
	HandlerType: (*AfAlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateAlert",
			Handler:    _AfAlertService_CalculateAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ag_algo/AfAlertService.proto",
}
