// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/ag_algo/FlightService.proto

package ag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlightService_GetPlannedTrack_FullMethodName            = "/com.vht.afad.afmessages.FlightService/getPlannedTrack"
	FlightService_GetFastForwardPlannedTrack_FullMethodName = "/com.vht.afad.afmessages.FlightService/getFastForwardPlannedTrack"
	FlightService_GetGuidedTrack_FullMethodName             = "/com.vht.afad.afmessages.FlightService/getGuidedTrack"
	FlightService_UpdateFlight_FullMethodName               = "/com.vht.afad.afmessages.FlightService/UpdateFlight"
)

// FlightServiceClient is the client API for FlightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Calculate the position of aircraft when it flies along a flight route at a specific time.
// sequence of planned track is the sequence of the last passed waypoint
// sequence = -1  -> if planned track has not passed the 1st wp yet
// sequence = i   -> planned track on turn arc i or segment [i][i+1]
// duration		duration since the flight started in second
// return	 	position of the planned track
type FlightServiceClient interface {
	// for direct guidance flight, return equal duration points
	// and the (mini) equal duration route (from planned track position to the last equal duration point)
	GetPlannedTrack(ctx context.Context, in *GRPCFlight, opts ...grpc.CallOption) (*PlannedTrackResponse, error)
	GetFastForwardPlannedTrack(ctx context.Context, in *PlannedTrackRequest, opts ...grpc.CallOption) (*PlannedTrackResponse, error)
	GetGuidedTrack(ctx context.Context, in *GuidedTrackRequest, opts ...grpc.CallOption) (*GRPCGeodeticState, error)
	UpdateFlight(ctx context.Context, in *GRPCFlight, opts ...grpc.CallOption) (*GRPCFlight, error)
}

type flightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightServiceClient(cc grpc.ClientConnInterface) FlightServiceClient {
	return &flightServiceClient{cc}
}

func (c *flightServiceClient) GetPlannedTrack(ctx context.Context, in *GRPCFlight, opts ...grpc.CallOption) (*PlannedTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlannedTrackResponse)
	err := c.cc.Invoke(ctx, FlightService_GetPlannedTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) GetFastForwardPlannedTrack(ctx context.Context, in *PlannedTrackRequest, opts ...grpc.CallOption) (*PlannedTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlannedTrackResponse)
	err := c.cc.Invoke(ctx, FlightService_GetFastForwardPlannedTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) GetGuidedTrack(ctx context.Context, in *GuidedTrackRequest, opts ...grpc.CallOption) (*GRPCGeodeticState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCGeodeticState)
	err := c.cc.Invoke(ctx, FlightService_GetGuidedTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flightServiceClient) UpdateFlight(ctx context.Context, in *GRPCFlight, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, FlightService_UpdateFlight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightServiceServer is the server API for FlightService service.
// All implementations must embed UnimplementedFlightServiceServer
// for forward compatibility.
//
// *
// Calculate the position of aircraft when it flies along a flight route at a specific time.
// sequence of planned track is the sequence of the last passed waypoint
// sequence = -1  -> if planned track has not passed the 1st wp yet
// sequence = i   -> planned track on turn arc i or segment [i][i+1]
// duration		duration since the flight started in second
// return	 	position of the planned track
type FlightServiceServer interface {
	// for direct guidance flight, return equal duration points
	// and the (mini) equal duration route (from planned track position to the last equal duration point)
	GetPlannedTrack(context.Context, *GRPCFlight) (*PlannedTrackResponse, error)
	GetFastForwardPlannedTrack(context.Context, *PlannedTrackRequest) (*PlannedTrackResponse, error)
	GetGuidedTrack(context.Context, *GuidedTrackRequest) (*GRPCGeodeticState, error)
	UpdateFlight(context.Context, *GRPCFlight) (*GRPCFlight, error)
	mustEmbedUnimplementedFlightServiceServer()
}

// UnimplementedFlightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlightServiceServer struct{}

func (UnimplementedFlightServiceServer) GetPlannedTrack(context.Context, *GRPCFlight) (*PlannedTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlannedTrack not implemented")
}
func (UnimplementedFlightServiceServer) GetFastForwardPlannedTrack(context.Context, *PlannedTrackRequest) (*PlannedTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFastForwardPlannedTrack not implemented")
}
func (UnimplementedFlightServiceServer) GetGuidedTrack(context.Context, *GuidedTrackRequest) (*GRPCGeodeticState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuidedTrack not implemented")
}
func (UnimplementedFlightServiceServer) UpdateFlight(context.Context, *GRPCFlight) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFlight not implemented")
}
func (UnimplementedFlightServiceServer) mustEmbedUnimplementedFlightServiceServer() {}
func (UnimplementedFlightServiceServer) testEmbeddedByValue()                       {}

// UnsafeFlightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightServiceServer will
// result in compilation errors.
type UnsafeFlightServiceServer interface {
	mustEmbedUnimplementedFlightServiceServer()
}

func RegisterFlightServiceServer(s grpc.ServiceRegistrar, srv FlightServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlightService_ServiceDesc, srv)
}

func _FlightService_GetPlannedTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCFlight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).GetPlannedTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_GetPlannedTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).GetPlannedTrack(ctx, req.(*GRPCFlight))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_GetFastForwardPlannedTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlannedTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).GetFastForwardPlannedTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_GetFastForwardPlannedTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).GetFastForwardPlannedTrack(ctx, req.(*PlannedTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_GetGuidedTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuidedTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).GetGuidedTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_GetGuidedTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).GetGuidedTrack(ctx, req.(*GuidedTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlightService_UpdateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCFlight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightServiceServer).UpdateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlightService_UpdateFlight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightServiceServer).UpdateFlight(ctx, req.(*GRPCFlight))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightService_ServiceDesc is the grpc.ServiceDesc for FlightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.vht.afad.afmessages.FlightService",
	HandlerType: (*FlightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getPlannedTrack",
			Handler:    _FlightService_GetPlannedTrack_Handler,
		},
		{
			MethodName: "getFastForwardPlannedTrack",
			Handler:    _FlightService_GetFastForwardPlannedTrack_Handler,
		},
		{
			MethodName: "getGuidedTrack",
			Handler:    _FlightService_GetGuidedTrack_Handler,
		},
		{
			MethodName: "UpdateFlight",
			Handler:    _FlightService_UpdateFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ag_algo/FlightService.proto",
}
