// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/ag_algo/InterceptService.proto

package ag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterceptService_CreateInterceptRouteListFromAirport_FullMethodName       = "/com.vht.afad.afmessages.InterceptService/createInterceptRouteListFromAirport"
	InterceptService_CreateInterceptRouteFromAirport_FullMethodName           = "/com.vht.afad.afmessages.InterceptService/createInterceptRouteFromAirport"
	InterceptService_CreateInterceptRouteListFromCombatPatrol_FullMethodName  = "/com.vht.afad.afmessages.InterceptService/createInterceptRouteListFromCombatPatrol"
	InterceptService_CreateInterceptRouteFromCombatPatrol_FullMethodName      = "/com.vht.afad.afmessages.InterceptService/createInterceptRouteFromCombatPatrol"
	InterceptService_UpdateInterceptRouteList_FullMethodName                  = "/com.vht.afad.afmessages.InterceptService/updateInterceptRouteList"
	InterceptService_UpdateInterceptRoute_FullMethodName                      = "/com.vht.afad.afmessages.InterceptService/updateInterceptRoute"
	InterceptService_EditInterceptRoute_FullMethodName                        = "/com.vht.afad.afmessages.InterceptService/editInterceptRoute"
	InterceptService_CalcInterceptionLineRadarFromAirport_FullMethodName      = "/com.vht.afad.afmessages.InterceptService/calcInterceptionLineRadarFromAirport"
	InterceptService_CalcInterceptionLineRadarFromCombatPatrol_FullMethodName = "/com.vht.afad.afmessages.InterceptService/calcInterceptionLineRadarFromCombatPatrol"
	InterceptService_CalcInterceptionLineProtection_FullMethodName            = "/com.vht.afad.afmessages.InterceptService/calcInterceptionLineProtection"
)

// InterceptServiceClient is the client API for InterceptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterceptServiceClient interface {
	// create the optimal intercept route for a given aircraft in a airport
	CreateInterceptRouteListFromAirport(ctx context.Context, in *FromAirportInputList, opts ...grpc.CallOption) (*GRPCFlightList, error)
	CreateInterceptRouteFromAirport(ctx context.Context, in *FromAirportInput, opts ...grpc.CallOption) (*GRPCFlightList, error)
	// create the optimal intercept route for a given aircraft on the Combat patrol
	CreateInterceptRouteListFromCombatPatrol(ctx context.Context, in *FromCombatPatrolInputList, opts ...grpc.CallOption) (*GRPCFlightList, error)
	CreateInterceptRouteFromCombatPatrol(ctx context.Context, in *FromCombatPatrolInput, opts ...grpc.CallOption) (*GRPCFlight, error)
	// update the Intercept Flight when the target change its action
	UpdateInterceptRouteList(ctx context.Context, in *UpdateInterceptInputList, opts ...grpc.CallOption) (*GRPCFlightList, error)
	UpdateInterceptRoute(ctx context.Context, in *UpdateInterceptInput, opts ...grpc.CallOption) (*GRPCFlight, error)
	// edit Intercept Flight when the user adds a fixed point on the route
	EditInterceptRoute(ctx context.Context, in *EditInterceptInput, opts ...grpc.CallOption) (*GRPCFlight, error)
	CalcInterceptionLineRadarFromAirport(ctx context.Context, in *ILFromAirportInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error)
	CalcInterceptionLineRadarFromCombatPatrol(ctx context.Context, in *ILFromCombatPatrolInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error)
	CalcInterceptionLineProtection(ctx context.Context, in *ILProtectionInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error)
}

type interceptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterceptServiceClient(cc grpc.ClientConnInterface) InterceptServiceClient {
	return &interceptServiceClient{cc}
}

func (c *interceptServiceClient) CreateInterceptRouteListFromAirport(ctx context.Context, in *FromAirportInputList, opts ...grpc.CallOption) (*GRPCFlightList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightList)
	err := c.cc.Invoke(ctx, InterceptService_CreateInterceptRouteListFromAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CreateInterceptRouteFromAirport(ctx context.Context, in *FromAirportInput, opts ...grpc.CallOption) (*GRPCFlightList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightList)
	err := c.cc.Invoke(ctx, InterceptService_CreateInterceptRouteFromAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CreateInterceptRouteListFromCombatPatrol(ctx context.Context, in *FromCombatPatrolInputList, opts ...grpc.CallOption) (*GRPCFlightList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightList)
	err := c.cc.Invoke(ctx, InterceptService_CreateInterceptRouteListFromCombatPatrol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CreateInterceptRouteFromCombatPatrol(ctx context.Context, in *FromCombatPatrolInput, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, InterceptService_CreateInterceptRouteFromCombatPatrol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) UpdateInterceptRouteList(ctx context.Context, in *UpdateInterceptInputList, opts ...grpc.CallOption) (*GRPCFlightList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightList)
	err := c.cc.Invoke(ctx, InterceptService_UpdateInterceptRouteList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) UpdateInterceptRoute(ctx context.Context, in *UpdateInterceptInput, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, InterceptService_UpdateInterceptRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) EditInterceptRoute(ctx context.Context, in *EditInterceptInput, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, InterceptService_EditInterceptRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CalcInterceptionLineRadarFromAirport(ctx context.Context, in *ILFromAirportInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCInterceptionLineOutput)
	err := c.cc.Invoke(ctx, InterceptService_CalcInterceptionLineRadarFromAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CalcInterceptionLineRadarFromCombatPatrol(ctx context.Context, in *ILFromCombatPatrolInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCInterceptionLineOutput)
	err := c.cc.Invoke(ctx, InterceptService_CalcInterceptionLineRadarFromCombatPatrol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interceptServiceClient) CalcInterceptionLineProtection(ctx context.Context, in *ILProtectionInput, opts ...grpc.CallOption) (*GRPCInterceptionLineOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCInterceptionLineOutput)
	err := c.cc.Invoke(ctx, InterceptService_CalcInterceptionLineProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterceptServiceServer is the server API for InterceptService service.
// All implementations must embed UnimplementedInterceptServiceServer
// for forward compatibility.
type InterceptServiceServer interface {
	// create the optimal intercept route for a given aircraft in a airport
	CreateInterceptRouteListFromAirport(context.Context, *FromAirportInputList) (*GRPCFlightList, error)
	CreateInterceptRouteFromAirport(context.Context, *FromAirportInput) (*GRPCFlightList, error)
	// create the optimal intercept route for a given aircraft on the Combat patrol
	CreateInterceptRouteListFromCombatPatrol(context.Context, *FromCombatPatrolInputList) (*GRPCFlightList, error)
	CreateInterceptRouteFromCombatPatrol(context.Context, *FromCombatPatrolInput) (*GRPCFlight, error)
	// update the Intercept Flight when the target change its action
	UpdateInterceptRouteList(context.Context, *UpdateInterceptInputList) (*GRPCFlightList, error)
	UpdateInterceptRoute(context.Context, *UpdateInterceptInput) (*GRPCFlight, error)
	// edit Intercept Flight when the user adds a fixed point on the route
	EditInterceptRoute(context.Context, *EditInterceptInput) (*GRPCFlight, error)
	CalcInterceptionLineRadarFromAirport(context.Context, *ILFromAirportInput) (*GRPCInterceptionLineOutput, error)
	CalcInterceptionLineRadarFromCombatPatrol(context.Context, *ILFromCombatPatrolInput) (*GRPCInterceptionLineOutput, error)
	CalcInterceptionLineProtection(context.Context, *ILProtectionInput) (*GRPCInterceptionLineOutput, error)
	mustEmbedUnimplementedInterceptServiceServer()
}

// UnimplementedInterceptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterceptServiceServer struct{}

func (UnimplementedInterceptServiceServer) CreateInterceptRouteListFromAirport(context.Context, *FromAirportInputList) (*GRPCFlightList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterceptRouteListFromAirport not implemented")
}
func (UnimplementedInterceptServiceServer) CreateInterceptRouteFromAirport(context.Context, *FromAirportInput) (*GRPCFlightList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterceptRouteFromAirport not implemented")
}
func (UnimplementedInterceptServiceServer) CreateInterceptRouteListFromCombatPatrol(context.Context, *FromCombatPatrolInputList) (*GRPCFlightList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterceptRouteListFromCombatPatrol not implemented")
}
func (UnimplementedInterceptServiceServer) CreateInterceptRouteFromCombatPatrol(context.Context, *FromCombatPatrolInput) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterceptRouteFromCombatPatrol not implemented")
}
func (UnimplementedInterceptServiceServer) UpdateInterceptRouteList(context.Context, *UpdateInterceptInputList) (*GRPCFlightList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInterceptRouteList not implemented")
}
func (UnimplementedInterceptServiceServer) UpdateInterceptRoute(context.Context, *UpdateInterceptInput) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInterceptRoute not implemented")
}
func (UnimplementedInterceptServiceServer) EditInterceptRoute(context.Context, *EditInterceptInput) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditInterceptRoute not implemented")
}
func (UnimplementedInterceptServiceServer) CalcInterceptionLineRadarFromAirport(context.Context, *ILFromAirportInput) (*GRPCInterceptionLineOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcInterceptionLineRadarFromAirport not implemented")
}
func (UnimplementedInterceptServiceServer) CalcInterceptionLineRadarFromCombatPatrol(context.Context, *ILFromCombatPatrolInput) (*GRPCInterceptionLineOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcInterceptionLineRadarFromCombatPatrol not implemented")
}
func (UnimplementedInterceptServiceServer) CalcInterceptionLineProtection(context.Context, *ILProtectionInput) (*GRPCInterceptionLineOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalcInterceptionLineProtection not implemented")
}
func (UnimplementedInterceptServiceServer) mustEmbedUnimplementedInterceptServiceServer() {}
func (UnimplementedInterceptServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterceptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterceptServiceServer will
// result in compilation errors.
type UnsafeInterceptServiceServer interface {
	mustEmbedUnimplementedInterceptServiceServer()
}

func RegisterInterceptServiceServer(s grpc.ServiceRegistrar, srv InterceptServiceServer) {
	// If the following call pancis, it indicates UnimplementedInterceptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterceptService_ServiceDesc, srv)
}

func _InterceptService_CreateInterceptRouteListFromAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromAirportInputList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CreateInterceptRouteListFromAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CreateInterceptRouteListFromAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CreateInterceptRouteListFromAirport(ctx, req.(*FromAirportInputList))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CreateInterceptRouteFromAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromAirportInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CreateInterceptRouteFromAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CreateInterceptRouteFromAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CreateInterceptRouteFromAirport(ctx, req.(*FromAirportInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CreateInterceptRouteListFromCombatPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromCombatPatrolInputList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CreateInterceptRouteListFromCombatPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CreateInterceptRouteListFromCombatPatrol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CreateInterceptRouteListFromCombatPatrol(ctx, req.(*FromCombatPatrolInputList))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CreateInterceptRouteFromCombatPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromCombatPatrolInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CreateInterceptRouteFromCombatPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CreateInterceptRouteFromCombatPatrol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CreateInterceptRouteFromCombatPatrol(ctx, req.(*FromCombatPatrolInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_UpdateInterceptRouteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterceptInputList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).UpdateInterceptRouteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_UpdateInterceptRouteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).UpdateInterceptRouteList(ctx, req.(*UpdateInterceptInputList))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_UpdateInterceptRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterceptInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).UpdateInterceptRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_UpdateInterceptRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).UpdateInterceptRoute(ctx, req.(*UpdateInterceptInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_EditInterceptRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInterceptInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).EditInterceptRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_EditInterceptRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).EditInterceptRoute(ctx, req.(*EditInterceptInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CalcInterceptionLineRadarFromAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ILFromAirportInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CalcInterceptionLineRadarFromAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CalcInterceptionLineRadarFromAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CalcInterceptionLineRadarFromAirport(ctx, req.(*ILFromAirportInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CalcInterceptionLineRadarFromCombatPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ILFromCombatPatrolInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CalcInterceptionLineRadarFromCombatPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CalcInterceptionLineRadarFromCombatPatrol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CalcInterceptionLineRadarFromCombatPatrol(ctx, req.(*ILFromCombatPatrolInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterceptService_CalcInterceptionLineProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ILProtectionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptServiceServer).CalcInterceptionLineProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterceptService_CalcInterceptionLineProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptServiceServer).CalcInterceptionLineProtection(ctx, req.(*ILProtectionInput))
	}
	return interceptor(ctx, in, info, handler)
}

// InterceptService_ServiceDesc is the grpc.ServiceDesc for InterceptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterceptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.vht.afad.afmessages.InterceptService",
	HandlerType: (*InterceptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createInterceptRouteListFromAirport",
			Handler:    _InterceptService_CreateInterceptRouteListFromAirport_Handler,
		},
		{
			MethodName: "createInterceptRouteFromAirport",
			Handler:    _InterceptService_CreateInterceptRouteFromAirport_Handler,
		},
		{
			MethodName: "createInterceptRouteListFromCombatPatrol",
			Handler:    _InterceptService_CreateInterceptRouteListFromCombatPatrol_Handler,
		},
		{
			MethodName: "createInterceptRouteFromCombatPatrol",
			Handler:    _InterceptService_CreateInterceptRouteFromCombatPatrol_Handler,
		},
		{
			MethodName: "updateInterceptRouteList",
			Handler:    _InterceptService_UpdateInterceptRouteList_Handler,
		},
		{
			MethodName: "updateInterceptRoute",
			Handler:    _InterceptService_UpdateInterceptRoute_Handler,
		},
		{
			MethodName: "editInterceptRoute",
			Handler:    _InterceptService_EditInterceptRoute_Handler,
		},
		{
			MethodName: "calcInterceptionLineRadarFromAirport",
			Handler:    _InterceptService_CalcInterceptionLineRadarFromAirport_Handler,
		},
		{
			MethodName: "calcInterceptionLineRadarFromCombatPatrol",
			Handler:    _InterceptService_CalcInterceptionLineRadarFromCombatPatrol_Handler,
		},
		{
			MethodName: "calcInterceptionLineProtection",
			Handler:    _InterceptService_CalcInterceptionLineProtection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ag_algo/InterceptService.proto",
}
