// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/ag_algo/Point.proto

package ag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCGeodeticPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"` //
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`   //
	Altitude  float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`   //
}

func (x *GRPCGeodeticPosition) Reset() {
	*x = GRPCGeodeticPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCGeodeticPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCGeodeticPosition) ProtoMessage() {}

func (x *GRPCGeodeticPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCGeodeticPosition.ProtoReflect.Descriptor instead.
func (*GRPCGeodeticPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCGeodeticPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GRPCGeodeticPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GRPCGeodeticPosition) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type GRPCVelocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed   float64 `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`     //
	Heading float64 `protobuf:"fixed64,2,opt,name=heading,proto3" json:"heading,omitempty"` //
}

func (x *GRPCVelocity) Reset() {
	*x = GRPCVelocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCVelocity) ProtoMessage() {}

func (x *GRPCVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCVelocity.ProtoReflect.Descriptor instead.
func (*GRPCVelocity) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCVelocity) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GRPCVelocity) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type GRPCGeodeticState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *GRPCGeodeticPosition `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` //
	Velocity *GRPCVelocity         `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"` //
}

func (x *GRPCGeodeticState) Reset() {
	*x = GRPCGeodeticState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCGeodeticState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCGeodeticState) ProtoMessage() {}

func (x *GRPCGeodeticState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCGeodeticState.ProtoReflect.Descriptor instead.
func (*GRPCGeodeticState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{2}
}

func (x *GRPCGeodeticState) GetPosition() *GRPCGeodeticPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GRPCGeodeticState) GetVelocity() *GRPCVelocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type GRPCPolarPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center   *GRPCGeodeticPosition `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`       //
	Range    float64               `protobuf:"fixed64,2,opt,name=range,proto3" json:"range,omitempty"`       //
	Azimuth  float64               `protobuf:"fixed64,3,opt,name=azimuth,proto3" json:"azimuth,omitempty"`   //
	Altitude float64               `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"` //
}

func (x *GRPCPolarPosition) Reset() {
	*x = GRPCPolarPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCPolarPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCPolarPosition) ProtoMessage() {}

func (x *GRPCPolarPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCPolarPosition.ProtoReflect.Descriptor instead.
func (*GRPCPolarPosition) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{3}
}

func (x *GRPCPolarPosition) GetCenter() *GRPCGeodeticPosition {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *GRPCPolarPosition) GetRange() float64 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *GRPCPolarPosition) GetAzimuth() float64 {
	if x != nil {
		return x.Azimuth
	}
	return 0
}

func (x *GRPCPolarPosition) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

type GRPCPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       //
	Sequence      int32              `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`          //
	Name          string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                   //
	GeodeticState *GRPCGeodeticState `protobuf:"bytes,4,opt,name=geodeticState,proto3" json:"geodeticState,omitempty"` //
}

func (x *GRPCPoint) Reset() {
	*x = GRPCPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCPoint) ProtoMessage() {}

func (x *GRPCPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCPoint.ProtoReflect.Descriptor instead.
func (*GRPCPoint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{4}
}

func (x *GRPCPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCPoint) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GRPCPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GRPCPoint) GetGeodeticState() *GRPCGeodeticState {
	if x != nil {
		return x.GeodeticState
	}
	return nil
}

type GRPCPointList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*GRPCGeodeticPosition `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"` //
}

func (x *GRPCPointList) Reset() {
	*x = GRPCPointList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCPointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCPointList) ProtoMessage() {}

func (x *GRPCPointList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCPointList.ProtoReflect.Descriptor instead.
func (*GRPCPointList) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{5}
}

func (x *GRPCPointList) GetPoints() []*GRPCGeodeticPosition {
	if x != nil {
		return x.Points
	}
	return nil
}

type GRPCPolygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           //
	Shell  *GRPCPointList   `protobuf:"bytes,2,opt,name=shell,proto3" json:"shell,omitempty"`     //
	Holes  []*GRPCPointList `protobuf:"bytes,3,rep,name=holes,proto3" json:"holes,omitempty"`     //
	Radius float64          `protobuf:"fixed64,4,opt,name=radius,proto3" json:"radius,omitempty"` //
}

func (x *GRPCPolygon) Reset() {
	*x = GRPCPolygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCPolygon) ProtoMessage() {}

func (x *GRPCPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Point_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCPolygon.ProtoReflect.Descriptor instead.
func (*GRPCPolygon) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Point_proto_rawDescGZIP(), []int{6}
}

func (x *GRPCPolygon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCPolygon) GetShell() *GRPCPointList {
	if x != nil {
		return x.Shell
	}
	return nil
}

func (x *GRPCPolygon) GetHoles() []*GRPCPointList {
	if x != nil {
		return x.Holes
	}
	return nil
}

func (x *GRPCPolygon) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

var File_pkg_proto_ag_algo_Point_proto protoreflect.FileDescriptor

var file_pkg_proto_ag_algo_Point_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x2f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x6c, 0x0a, 0x14, 0x47, 0x52, 0x50, 0x43,
	0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x6c,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x47, 0x52, 0x50, 0x43, 0x56, 0x65,
	0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x47, 0x52, 0x50, 0x43, 0x47,
	0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f,
	0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x22, 0xa6, 0x01, 0x0a, 0x11, 0x47,
	0x52, 0x50, 0x43, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x45, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e,
	0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x47,
	0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x47, 0x52, 0x50, 0x43, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x50, 0x0a, 0x0d, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x0d, 0x47, 0x52, 0x50, 0x43, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61,
	0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47,
	0x52, 0x50, 0x43, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x0b,
	0x47, 0x52, 0x50, 0x43, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x05, 0x73,
	0x68, 0x65, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x3c, 0x0a, 0x05, 0x68, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x05, 0x68, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ag_algo_Point_proto_rawDescOnce sync.Once
	file_pkg_proto_ag_algo_Point_proto_rawDescData = file_pkg_proto_ag_algo_Point_proto_rawDesc
)

func file_pkg_proto_ag_algo_Point_proto_rawDescGZIP() []byte {
	file_pkg_proto_ag_algo_Point_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ag_algo_Point_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ag_algo_Point_proto_rawDescData)
	})
	return file_pkg_proto_ag_algo_Point_proto_rawDescData
}

var file_pkg_proto_ag_algo_Point_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_ag_algo_Point_proto_goTypes = []interface{}{
	(*GRPCGeodeticPosition)(nil), // 0: com.vht.afad.afmessages.GRPCGeodeticPosition
	(*GRPCVelocity)(nil),         // 1: com.vht.afad.afmessages.GRPCVelocity
	(*GRPCGeodeticState)(nil),    // 2: com.vht.afad.afmessages.GRPCGeodeticState
	(*GRPCPolarPosition)(nil),    // 3: com.vht.afad.afmessages.GRPCPolarPosition
	(*GRPCPoint)(nil),            // 4: com.vht.afad.afmessages.GRPCPoint
	(*GRPCPointList)(nil),        // 5: com.vht.afad.afmessages.GRPCPointList
	(*GRPCPolygon)(nil),          // 6: com.vht.afad.afmessages.GRPCPolygon
}
var file_pkg_proto_ag_algo_Point_proto_depIdxs = []int32{
	0, // 0: com.vht.afad.afmessages.GRPCGeodeticState.position:type_name -> com.vht.afad.afmessages.GRPCGeodeticPosition
	1, // 1: com.vht.afad.afmessages.GRPCGeodeticState.velocity:type_name -> com.vht.afad.afmessages.GRPCVelocity
	0, // 2: com.vht.afad.afmessages.GRPCPolarPosition.center:type_name -> com.vht.afad.afmessages.GRPCGeodeticPosition
	2, // 3: com.vht.afad.afmessages.GRPCPoint.geodeticState:type_name -> com.vht.afad.afmessages.GRPCGeodeticState
	0, // 4: com.vht.afad.afmessages.GRPCPointList.points:type_name -> com.vht.afad.afmessages.GRPCGeodeticPosition
	5, // 5: com.vht.afad.afmessages.GRPCPolygon.shell:type_name -> com.vht.afad.afmessages.GRPCPointList
	5, // 6: com.vht.afad.afmessages.GRPCPolygon.holes:type_name -> com.vht.afad.afmessages.GRPCPointList
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_ag_algo_Point_proto_init() }
func file_pkg_proto_ag_algo_Point_proto_init() {
	if File_pkg_proto_ag_algo_Point_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ag_algo_Point_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCGeodeticPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCVelocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCGeodeticState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCPolarPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCPointList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_Point_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCPolygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ag_algo_Point_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ag_algo_Point_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ag_algo_Point_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ag_algo_Point_proto_msgTypes,
	}.Build()
	File_pkg_proto_ag_algo_Point_proto = out.File
	file_pkg_proto_ag_algo_Point_proto_rawDesc = nil
	file_pkg_proto_ag_algo_Point_proto_goTypes = nil
	file_pkg_proto_ag_algo_Point_proto_depIdxs = nil
}
