// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/ag_algo/RouteRequest.proto

package ag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route *GRPCFlightRoute `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"` //
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRouteRequest) GetRoute() *GRPCFlightRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

type EditRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldRoute *GRPCFlightRoute `protobuf:"bytes,1,opt,name=oldRoute,proto3" json:"oldRoute,omitempty"` //
	NewRoute *GRPCFlightRoute `protobuf:"bytes,2,opt,name=newRoute,proto3" json:"newRoute,omitempty"` //
}

func (x *EditRouteRequest) Reset() {
	*x = EditRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRouteRequest) ProtoMessage() {}

func (x *EditRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRouteRequest.ProtoReflect.Descriptor instead.
func (*EditRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{1}
}

func (x *EditRouteRequest) GetOldRoute() *GRPCFlightRoute {
	if x != nil {
		return x.OldRoute
	}
	return nil
}

func (x *EditRouteRequest) GetNewRoute() *GRPCFlightRoute {
	if x != nil {
		return x.NewRoute
	}
	return nil
}

type CreateFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *GRPCFlight `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"` //
}

func (x *CreateFlightRequest) Reset() {
	*x = CreateFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlightRequest) ProtoMessage() {}

func (x *CreateFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlightRequest.ProtoReflect.Descriptor instead.
func (*CreateFlightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFlightRequest) GetFlight() *GRPCFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

type EditFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldFlight *GRPCFlight `protobuf:"bytes,1,opt,name=oldFlight,proto3" json:"oldFlight,omitempty"` //
	NewFlight *GRPCFlight `protobuf:"bytes,2,opt,name=newFlight,proto3" json:"newFlight,omitempty"` //
}

func (x *EditFlightRequest) Reset() {
	*x = EditFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFlightRequest) ProtoMessage() {}

func (x *EditFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFlightRequest.ProtoReflect.Descriptor instead.
func (*EditFlightRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{3}
}

func (x *EditFlightRequest) GetOldFlight() *GRPCFlight {
	if x != nil {
		return x.OldFlight
	}
	return nil
}

func (x *EditFlightRequest) GetNewFlight() *GRPCFlight {
	if x != nil {
		return x.NewFlight
	}
	return nil
}

type DigitizedArc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Waypoints []*GRPCWaypoint `protobuf:"bytes,1,rep,name=waypoints,proto3" json:"waypoints,omitempty"` //
}

func (x *DigitizedArc) Reset() {
	*x = DigitizedArc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DigitizedArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitizedArc) ProtoMessage() {}

func (x *DigitizedArc) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitizedArc.ProtoReflect.Descriptor instead.
func (*DigitizedArc) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{4}
}

func (x *DigitizedArc) GetWaypoints() []*GRPCWaypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

type LandingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight *GRPCFlight        `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"` //
	Track  *GRPCGeodeticState `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`   //
}

func (x *LandingRequest) Reset() {
	*x = LandingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandingRequest) ProtoMessage() {}

func (x *LandingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandingRequest.ProtoReflect.Descriptor instead.
func (*LandingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{5}
}

func (x *LandingRequest) GetFlight() *GRPCFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *LandingRequest) GetTrack() *GRPCGeodeticState {
	if x != nil {
		return x.Track
	}
	return nil
}

type LandingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LandingRoutes []*GRPCFlightRoute `protobuf:"bytes,1,rep,name=landingRoutes,proto3" json:"landingRoutes,omitempty"` //
}

func (x *LandingResponse) Reset() {
	*x = LandingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandingResponse) ProtoMessage() {}

func (x *LandingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandingResponse.ProtoReflect.Descriptor instead.
func (*LandingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{6}
}

func (x *LandingResponse) GetLandingRoutes() []*GRPCFlightRoute {
	if x != nil {
		return x.LandingRoutes
	}
	return nil
}

type EditHandoverLineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route            *GRPCFlightRoute `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`                       //
	HandoverLineName string           `protobuf:"bytes,2,opt,name=handoverLineName,proto3" json:"handoverLineName,omitempty"` //
}

func (x *EditHandoverLineRequest) Reset() {
	*x = EditHandoverLineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditHandoverLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditHandoverLineRequest) ProtoMessage() {}

func (x *EditHandoverLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditHandoverLineRequest.ProtoReflect.Descriptor instead.
func (*EditHandoverLineRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{7}
}

func (x *EditHandoverLineRequest) GetRoute() *GRPCFlightRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *EditHandoverLineRequest) GetHandoverLineName() string {
	if x != nil {
		return x.HandoverLineName
	}
	return ""
}

type CorrectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight        *GRPCFlight        `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`                                                               //
	Track         *GRPCGeodeticState `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`                                                                 //
	DeviateAngle  float64            `protobuf:"fixed64,3,opt,name=deviateAngle,proto3" json:"deviateAngle,omitempty"`                                                 //
	TurnDirection GRPCTurnDirection  `protobuf:"varint,4,opt,name=turnDirection,proto3,enum=com.vht.afad.afmessages.GRPCTurnDirection" json:"turnDirection,omitempty"` //
	BankAngle     float64            `protobuf:"fixed64,5,opt,name=bankAngle,proto3" json:"bankAngle,omitempty"`                                                       //
}

func (x *CorrectionRequest) Reset() {
	*x = CorrectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionRequest) ProtoMessage() {}

func (x *CorrectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionRequest.ProtoReflect.Descriptor instead.
func (*CorrectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{8}
}

func (x *CorrectionRequest) GetFlight() *GRPCFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *CorrectionRequest) GetTrack() *GRPCGeodeticState {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *CorrectionRequest) GetDeviateAngle() float64 {
	if x != nil {
		return x.DeviateAngle
	}
	return 0
}

func (x *CorrectionRequest) GetTurnDirection() GRPCTurnDirection {
	if x != nil {
		return x.TurnDirection
	}
	return GRPCTurnDirection_TURN_DIRECTION_UNKNOWN
}

func (x *CorrectionRequest) GetBankAngle() float64 {
	if x != nil {
		return x.BankAngle
	}
	return 0
}

type CorrectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight   *GRPCFlight `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`       //
	Speed    float64     `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`       //
	Heading  float64     `protobuf:"fixed64,3,opt,name=heading,proto3" json:"heading,omitempty"`   //
	Duration float64     `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"` //
}

func (x *CorrectionResponse) Reset() {
	*x = CorrectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionResponse) ProtoMessage() {}

func (x *CorrectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionResponse.ProtoReflect.Descriptor instead.
func (*CorrectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{9}
}

func (x *CorrectionResponse) GetFlight() *GRPCFlight {
	if x != nil {
		return x.Flight
	}
	return nil
}

func (x *CorrectionResponse) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CorrectionResponse) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *CorrectionResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CorrectionResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*CorrectionResponse `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"` //
}

func (x *CorrectionResponses) Reset() {
	*x = CorrectionResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrectionResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrectionResponses) ProtoMessage() {}

func (x *CorrectionResponses) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrectionResponses.ProtoReflect.Descriptor instead.
func (*CorrectionResponses) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP(), []int{10}
}

func (x *CorrectionResponses) GetFlights() []*CorrectionResponse {
	if x != nil {
		return x.Flights
	}
	return nil
}

var File_pkg_proto_ag_algo_RouteRequest_proto protoreflect.FileDescriptor

var file_pkg_proto_ag_algo_RouteRequest_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x2f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e,
	0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a,
	0x23, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61, 0x6c,
	0x67, 0x6f, 0x2f, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x54, 0x75, 0x72, 0x6e, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x9e,
	0x01, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e,
	0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x08, 0x6f, 0x6c, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x08, 0x6e, 0x65, 0x77,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22,
	0x52, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74,
	0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x45, 0x64, 0x69, 0x74, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x09, 0x6f, 0x6c, 0x64,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x09, 0x6f, 0x6c, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x41, 0x0a, 0x09,
	0x6e, 0x65, 0x77, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61,
	0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x53, 0x0a, 0x0c, 0x44, 0x69, 0x67, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x64, 0x41, 0x72, 0x63, 0x12,
	0x43, 0x0a, 0x09, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61,
	0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50,
	0x43, 0x57, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x77, 0x61, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x0e, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68,
	0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x40, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66,
	0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52,
	0x50, 0x43, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x61, 0x0a, 0x0f, 0x4c, 0x61, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x6c, 0x61, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e,
	0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x0d, 0x6c, 0x61, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x17, 0x45, 0x64,
	0x69, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6f, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61,
	0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47,
	0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x68, 0x61, 0x6e, 0x64, 0x6f, 0x76, 0x65,
	0x72, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x68, 0x61, 0x6e, 0x64, 0x6f, 0x76, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0xa6, 0x02, 0x0a, 0x11, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68,
	0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x40, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66,
	0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52,
	0x50, 0x43, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x61, 0x74,
	0x65, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x65,
	0x76, 0x69, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x74, 0x75,
	0x72, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64,
	0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x54, 0x75, 0x72, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74,
	0x75, 0x72, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x61, 0x6e, 0x6b, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x12, 0x43,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64,
	0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x13, 0x43, 0x6f,
	0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x12, 0x45, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61,
	0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x72,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x61, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ag_algo_RouteRequest_proto_rawDescOnce sync.Once
	file_pkg_proto_ag_algo_RouteRequest_proto_rawDescData = file_pkg_proto_ag_algo_RouteRequest_proto_rawDesc
)

func file_pkg_proto_ag_algo_RouteRequest_proto_rawDescGZIP() []byte {
	file_pkg_proto_ag_algo_RouteRequest_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ag_algo_RouteRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ag_algo_RouteRequest_proto_rawDescData)
	})
	return file_pkg_proto_ag_algo_RouteRequest_proto_rawDescData
}

var file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_ag_algo_RouteRequest_proto_goTypes = []interface{}{
	(*CreateRouteRequest)(nil),      // 0: com.vht.afad.afmessages.CreateRouteRequest
	(*EditRouteRequest)(nil),        // 1: com.vht.afad.afmessages.EditRouteRequest
	(*CreateFlightRequest)(nil),     // 2: com.vht.afad.afmessages.CreateFlightRequest
	(*EditFlightRequest)(nil),       // 3: com.vht.afad.afmessages.EditFlightRequest
	(*DigitizedArc)(nil),            // 4: com.vht.afad.afmessages.DigitizedArc
	(*LandingRequest)(nil),          // 5: com.vht.afad.afmessages.LandingRequest
	(*LandingResponse)(nil),         // 6: com.vht.afad.afmessages.LandingResponse
	(*EditHandoverLineRequest)(nil), // 7: com.vht.afad.afmessages.EditHandoverLineRequest
	(*CorrectionRequest)(nil),       // 8: com.vht.afad.afmessages.CorrectionRequest
	(*CorrectionResponse)(nil),      // 9: com.vht.afad.afmessages.CorrectionResponse
	(*CorrectionResponses)(nil),     // 10: com.vht.afad.afmessages.CorrectionResponses
	(*GRPCFlightRoute)(nil),         // 11: com.vht.afad.afmessages.GRPCFlightRoute
	(*GRPCFlight)(nil),              // 12: com.vht.afad.afmessages.GRPCFlight
	(*GRPCWaypoint)(nil),            // 13: com.vht.afad.afmessages.GRPCWaypoint
	(*GRPCGeodeticState)(nil),       // 14: com.vht.afad.afmessages.GRPCGeodeticState
	(GRPCTurnDirection)(0),          // 15: com.vht.afad.afmessages.GRPCTurnDirection
}
var file_pkg_proto_ag_algo_RouteRequest_proto_depIdxs = []int32{
	11, // 0: com.vht.afad.afmessages.CreateRouteRequest.route:type_name -> com.vht.afad.afmessages.GRPCFlightRoute
	11, // 1: com.vht.afad.afmessages.EditRouteRequest.oldRoute:type_name -> com.vht.afad.afmessages.GRPCFlightRoute
	11, // 2: com.vht.afad.afmessages.EditRouteRequest.newRoute:type_name -> com.vht.afad.afmessages.GRPCFlightRoute
	12, // 3: com.vht.afad.afmessages.CreateFlightRequest.flight:type_name -> com.vht.afad.afmessages.GRPCFlight
	12, // 4: com.vht.afad.afmessages.EditFlightRequest.oldFlight:type_name -> com.vht.afad.afmessages.GRPCFlight
	12, // 5: com.vht.afad.afmessages.EditFlightRequest.newFlight:type_name -> com.vht.afad.afmessages.GRPCFlight
	13, // 6: com.vht.afad.afmessages.DigitizedArc.waypoints:type_name -> com.vht.afad.afmessages.GRPCWaypoint
	12, // 7: com.vht.afad.afmessages.LandingRequest.flight:type_name -> com.vht.afad.afmessages.GRPCFlight
	14, // 8: com.vht.afad.afmessages.LandingRequest.track:type_name -> com.vht.afad.afmessages.GRPCGeodeticState
	11, // 9: com.vht.afad.afmessages.LandingResponse.landingRoutes:type_name -> com.vht.afad.afmessages.GRPCFlightRoute
	11, // 10: com.vht.afad.afmessages.EditHandoverLineRequest.route:type_name -> com.vht.afad.afmessages.GRPCFlightRoute
	12, // 11: com.vht.afad.afmessages.CorrectionRequest.flight:type_name -> com.vht.afad.afmessages.GRPCFlight
	14, // 12: com.vht.afad.afmessages.CorrectionRequest.track:type_name -> com.vht.afad.afmessages.GRPCGeodeticState
	15, // 13: com.vht.afad.afmessages.CorrectionRequest.turnDirection:type_name -> com.vht.afad.afmessages.GRPCTurnDirection
	12, // 14: com.vht.afad.afmessages.CorrectionResponse.flight:type_name -> com.vht.afad.afmessages.GRPCFlight
	9,  // 15: com.vht.afad.afmessages.CorrectionResponses.flights:type_name -> com.vht.afad.afmessages.CorrectionResponse
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_proto_ag_algo_RouteRequest_proto_init() }
func file_pkg_proto_ag_algo_RouteRequest_proto_init() {
	if File_pkg_proto_ag_algo_RouteRequest_proto != nil {
		return
	}
	file_pkg_proto_ag_algo_FlightRoute_proto_init()
	file_pkg_proto_ag_algo_Flight_proto_init()
	file_pkg_proto_ag_algo_Waypoint_proto_init()
	file_pkg_proto_ag_algo_Point_proto_init()
	file_pkg_proto_ag_algo_Turnpoint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DigitizedArc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditHandoverLineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrectionResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ag_algo_RouteRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ag_algo_RouteRequest_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ag_algo_RouteRequest_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ag_algo_RouteRequest_proto_msgTypes,
	}.Build()
	File_pkg_proto_ag_algo_RouteRequest_proto = out.File
	file_pkg_proto_ag_algo_RouteRequest_proto_rawDesc = nil
	file_pkg_proto_ag_algo_RouteRequest_proto_goTypes = nil
	file_pkg_proto_ag_algo_RouteRequest_proto_depIdxs = nil
}
