// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/ag_algo/RouteCalculatorService.proto

package ag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteCalculatorService_CreateRoute_FullMethodName                      = "/com.vht.afad.afmessages.RouteCalculatorService/CreateRoute"
	RouteCalculatorService_EditRoute_FullMethodName                        = "/com.vht.afad.afmessages.RouteCalculatorService/EditRoute"
	RouteCalculatorService_CreateFlight_FullMethodName                     = "/com.vht.afad.afmessages.RouteCalculatorService/CreateFlight"
	RouteCalculatorService_EditFlight_FullMethodName                       = "/com.vht.afad.afmessages.RouteCalculatorService/EditFlight"
	RouteCalculatorService_GetSafeAltitude_FullMethodName                  = "/com.vht.afad.afmessages.RouteCalculatorService/GetSafeAltitude"
	RouteCalculatorService_GetCorrectionWave_FullMethodName                = "/com.vht.afad.afmessages.RouteCalculatorService/GetCorrectionWave"
	RouteCalculatorService_GetCorrectionVelocity_FullMethodName            = "/com.vht.afad.afmessages.RouteCalculatorService/GetCorrectionVelocity"
	RouteCalculatorService_GetAllCorrectionWave_FullMethodName             = "/com.vht.afad.afmessages.RouteCalculatorService/GetAllCorrectionWave"
	RouteCalculatorService_GetAllCorrectionVelocity_FullMethodName         = "/com.vht.afad.afmessages.RouteCalculatorService/GetAllCorrectionVelocity"
	RouteCalculatorService_DirectGuidance_FullMethodName                   = "/com.vht.afad.afmessages.RouteCalculatorService/DirectGuidance"
	RouteCalculatorService_GetLandingSolution_FullMethodName               = "/com.vht.afad.afmessages.RouteCalculatorService/getLandingSolution"
	RouteCalculatorService_GetLandingSolutionForDestAirport_FullMethodName = "/com.vht.afad.afmessages.RouteCalculatorService/getLandingSolutionForDestAirport"
)

// RouteCalculatorServiceClient is the client API for RouteCalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteCalculatorServiceClient interface {
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*GRPCFlightRoute, error)
	EditRoute(ctx context.Context, in *EditRouteRequest, opts ...grpc.CallOption) (*GRPCFlightRoute, error)
	CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*GRPCFlight, error)
	EditFlight(ctx context.Context, in *EditFlightRequest, opts ...grpc.CallOption) (*GRPCFlight, error)
	GetSafeAltitude(ctx context.Context, in *GRPCFlightRoute, opts ...grpc.CallOption) (*GRPCFlightRoute, error)
	GetCorrectionWave(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponse, error)
	GetCorrectionVelocity(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponse, error)
	GetAllCorrectionWave(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponses, error)
	GetAllCorrectionVelocity(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponses, error)
	DirectGuidance(ctx context.Context, in *DirectGuidanceCommand, opts ...grpc.CallOption) (*GRPCFlight, error)
	GetLandingSolution(ctx context.Context, in *LandingRequest, opts ...grpc.CallOption) (*LandingResponse, error)
	GetLandingSolutionForDestAirport(ctx context.Context, in *LandingRequest, opts ...grpc.CallOption) (*LandingResponse, error)
}

type routeCalculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteCalculatorServiceClient(cc grpc.ClientConnInterface) RouteCalculatorServiceClient {
	return &routeCalculatorServiceClient{cc}
}

func (c *routeCalculatorServiceClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*GRPCFlightRoute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightRoute)
	err := c.cc.Invoke(ctx, RouteCalculatorService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) EditRoute(ctx context.Context, in *EditRouteRequest, opts ...grpc.CallOption) (*GRPCFlightRoute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightRoute)
	err := c.cc.Invoke(ctx, RouteCalculatorService_EditRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) CreateFlight(ctx context.Context, in *CreateFlightRequest, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, RouteCalculatorService_CreateFlight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) EditFlight(ctx context.Context, in *EditFlightRequest, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, RouteCalculatorService_EditFlight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetSafeAltitude(ctx context.Context, in *GRPCFlightRoute, opts ...grpc.CallOption) (*GRPCFlightRoute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlightRoute)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetSafeAltitude_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetCorrectionWave(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrectionResponse)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetCorrectionWave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetCorrectionVelocity(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrectionResponse)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetCorrectionVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetAllCorrectionWave(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrectionResponses)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetAllCorrectionWave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetAllCorrectionVelocity(ctx context.Context, in *CorrectionRequest, opts ...grpc.CallOption) (*CorrectionResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrectionResponses)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetAllCorrectionVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) DirectGuidance(ctx context.Context, in *DirectGuidanceCommand, opts ...grpc.CallOption) (*GRPCFlight, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCFlight)
	err := c.cc.Invoke(ctx, RouteCalculatorService_DirectGuidance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetLandingSolution(ctx context.Context, in *LandingRequest, opts ...grpc.CallOption) (*LandingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LandingResponse)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetLandingSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeCalculatorServiceClient) GetLandingSolutionForDestAirport(ctx context.Context, in *LandingRequest, opts ...grpc.CallOption) (*LandingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LandingResponse)
	err := c.cc.Invoke(ctx, RouteCalculatorService_GetLandingSolutionForDestAirport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteCalculatorServiceServer is the server API for RouteCalculatorService service.
// All implementations must embed UnimplementedRouteCalculatorServiceServer
// for forward compatibility.
type RouteCalculatorServiceServer interface {
	CreateRoute(context.Context, *CreateRouteRequest) (*GRPCFlightRoute, error)
	EditRoute(context.Context, *EditRouteRequest) (*GRPCFlightRoute, error)
	CreateFlight(context.Context, *CreateFlightRequest) (*GRPCFlight, error)
	EditFlight(context.Context, *EditFlightRequest) (*GRPCFlight, error)
	GetSafeAltitude(context.Context, *GRPCFlightRoute) (*GRPCFlightRoute, error)
	GetCorrectionWave(context.Context, *CorrectionRequest) (*CorrectionResponse, error)
	GetCorrectionVelocity(context.Context, *CorrectionRequest) (*CorrectionResponse, error)
	GetAllCorrectionWave(context.Context, *CorrectionRequest) (*CorrectionResponses, error)
	GetAllCorrectionVelocity(context.Context, *CorrectionRequest) (*CorrectionResponses, error)
	DirectGuidance(context.Context, *DirectGuidanceCommand) (*GRPCFlight, error)
	GetLandingSolution(context.Context, *LandingRequest) (*LandingResponse, error)
	GetLandingSolutionForDestAirport(context.Context, *LandingRequest) (*LandingResponse, error)
	mustEmbedUnimplementedRouteCalculatorServiceServer()
}

// UnimplementedRouteCalculatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteCalculatorServiceServer struct{}

func (UnimplementedRouteCalculatorServiceServer) CreateRoute(context.Context, *CreateRouteRequest) (*GRPCFlightRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) EditRoute(context.Context, *EditRouteRequest) (*GRPCFlightRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRoute not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) CreateFlight(context.Context, *CreateFlightRequest) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlight not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) EditFlight(context.Context, *EditFlightRequest) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditFlight not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetSafeAltitude(context.Context, *GRPCFlightRoute) (*GRPCFlightRoute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSafeAltitude not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetCorrectionWave(context.Context, *CorrectionRequest) (*CorrectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCorrectionWave not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetCorrectionVelocity(context.Context, *CorrectionRequest) (*CorrectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCorrectionVelocity not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetAllCorrectionWave(context.Context, *CorrectionRequest) (*CorrectionResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCorrectionWave not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetAllCorrectionVelocity(context.Context, *CorrectionRequest) (*CorrectionResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCorrectionVelocity not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) DirectGuidance(context.Context, *DirectGuidanceCommand) (*GRPCFlight, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirectGuidance not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetLandingSolution(context.Context, *LandingRequest) (*LandingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLandingSolution not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) GetLandingSolutionForDestAirport(context.Context, *LandingRequest) (*LandingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLandingSolutionForDestAirport not implemented")
}
func (UnimplementedRouteCalculatorServiceServer) mustEmbedUnimplementedRouteCalculatorServiceServer() {
}
func (UnimplementedRouteCalculatorServiceServer) testEmbeddedByValue() {}

// UnsafeRouteCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteCalculatorServiceServer will
// result in compilation errors.
type UnsafeRouteCalculatorServiceServer interface {
	mustEmbedUnimplementedRouteCalculatorServiceServer()
}

func RegisterRouteCalculatorServiceServer(s grpc.ServiceRegistrar, srv RouteCalculatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouteCalculatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteCalculatorService_ServiceDesc, srv)
}

func _RouteCalculatorService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_EditRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).EditRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_EditRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).EditRoute(ctx, req.(*EditRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_CreateFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).CreateFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_CreateFlight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).CreateFlight(ctx, req.(*CreateFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_EditFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).EditFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_EditFlight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).EditFlight(ctx, req.(*EditFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetSafeAltitude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCFlightRoute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetSafeAltitude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetSafeAltitude_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetSafeAltitude(ctx, req.(*GRPCFlightRoute))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetCorrectionWave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetCorrectionWave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetCorrectionWave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetCorrectionWave(ctx, req.(*CorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetCorrectionVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetCorrectionVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetCorrectionVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetCorrectionVelocity(ctx, req.(*CorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetAllCorrectionWave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetAllCorrectionWave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetAllCorrectionWave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetAllCorrectionWave(ctx, req.(*CorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetAllCorrectionVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetAllCorrectionVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetAllCorrectionVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetAllCorrectionVelocity(ctx, req.(*CorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_DirectGuidance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectGuidanceCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).DirectGuidance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_DirectGuidance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).DirectGuidance(ctx, req.(*DirectGuidanceCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetLandingSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetLandingSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetLandingSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetLandingSolution(ctx, req.(*LandingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteCalculatorService_GetLandingSolutionForDestAirport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteCalculatorServiceServer).GetLandingSolutionForDestAirport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteCalculatorService_GetLandingSolutionForDestAirport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteCalculatorServiceServer).GetLandingSolutionForDestAirport(ctx, req.(*LandingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteCalculatorService_ServiceDesc is the grpc.ServiceDesc for RouteCalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteCalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.vht.afad.afmessages.RouteCalculatorService",
	HandlerType: (*RouteCalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoute",
			Handler:    _RouteCalculatorService_CreateRoute_Handler,
		},
		{
			MethodName: "EditRoute",
			Handler:    _RouteCalculatorService_EditRoute_Handler,
		},
		{
			MethodName: "CreateFlight",
			Handler:    _RouteCalculatorService_CreateFlight_Handler,
		},
		{
			MethodName: "EditFlight",
			Handler:    _RouteCalculatorService_EditFlight_Handler,
		},
		{
			MethodName: "GetSafeAltitude",
			Handler:    _RouteCalculatorService_GetSafeAltitude_Handler,
		},
		{
			MethodName: "GetCorrectionWave",
			Handler:    _RouteCalculatorService_GetCorrectionWave_Handler,
		},
		{
			MethodName: "GetCorrectionVelocity",
			Handler:    _RouteCalculatorService_GetCorrectionVelocity_Handler,
		},
		{
			MethodName: "GetAllCorrectionWave",
			Handler:    _RouteCalculatorService_GetAllCorrectionWave_Handler,
		},
		{
			MethodName: "GetAllCorrectionVelocity",
			Handler:    _RouteCalculatorService_GetAllCorrectionVelocity_Handler,
		},
		{
			MethodName: "DirectGuidance",
			Handler:    _RouteCalculatorService_DirectGuidance_Handler,
		},
		{
			MethodName: "getLandingSolution",
			Handler:    _RouteCalculatorService_GetLandingSolution_Handler,
		},
		{
			MethodName: "getLandingSolutionForDestAirport",
			Handler:    _RouteCalculatorService_GetLandingSolutionForDestAirport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ag_algo/RouteCalculatorService.proto",
}
