// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/ag_algo/RSRadar.proto

package ag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCRSRadar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             //
	Name     string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         //
	Position *GRPCGeodeticPosition   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"` //
	FSup     string                  `protobuf:"bytes,4,opt,name=fSup,proto3" json:"fSup,omitempty"`         //
	Type     int32                   `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`        //`json:"type" bson:"type"`
	Coverage []*GRPCGeodeticPosition `protobuf:"bytes,6,rep,name=coverage,proto3" json:"coverage,omitempty"` //
	UnitID   string                  `protobuf:"bytes,7,opt,name=UnitID,proto3" json:"UnitID,omitempty"`     //`json:"unit_id" bson:"unit_id"`
	Radius   float64                 `protobuf:"fixed64,8,opt,name=radius,proto3" json:"radius,omitempty"`   //
}

func (x *GRPCRSRadar) Reset() {
	*x = GRPCRSRadar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_RSRadar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCRSRadar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCRSRadar) ProtoMessage() {}

func (x *GRPCRSRadar) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_RSRadar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCRSRadar.ProtoReflect.Descriptor instead.
func (*GRPCRSRadar) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_RSRadar_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCRSRadar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCRSRadar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GRPCRSRadar) GetPosition() *GRPCGeodeticPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GRPCRSRadar) GetFSup() string {
	if x != nil {
		return x.FSup
	}
	return ""
}

func (x *GRPCRSRadar) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GRPCRSRadar) GetCoverage() []*GRPCGeodeticPosition {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *GRPCRSRadar) GetUnitID() string {
	if x != nil {
		return x.UnitID
	}
	return ""
}

func (x *GRPCRSRadar) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

var File_pkg_proto_ag_algo_RSRadar_proto protoreflect.FileDescriptor

var file_pkg_proto_ag_algo_RSRadar_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x2f, 0x52, 0x53, 0x52, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e,
	0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1d, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x0b, 0x47, 0x52,
	0x50, 0x43, 0x52, 0x53, 0x52, 0x61, 0x64, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61,
	0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65,
	0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x53, 0x75, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x53, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x49, 0x0a, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61,
	0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50,
	0x43, 0x47, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x6e, 0x69, 0x74, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x6e, 0x69,
	0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ag_algo_RSRadar_proto_rawDescOnce sync.Once
	file_pkg_proto_ag_algo_RSRadar_proto_rawDescData = file_pkg_proto_ag_algo_RSRadar_proto_rawDesc
)

func file_pkg_proto_ag_algo_RSRadar_proto_rawDescGZIP() []byte {
	file_pkg_proto_ag_algo_RSRadar_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ag_algo_RSRadar_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ag_algo_RSRadar_proto_rawDescData)
	})
	return file_pkg_proto_ag_algo_RSRadar_proto_rawDescData
}

var file_pkg_proto_ag_algo_RSRadar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_ag_algo_RSRadar_proto_goTypes = []interface{}{
	(*GRPCRSRadar)(nil),          // 0: com.vht.afad.afmessages.GRPCRSRadar
	(*GRPCGeodeticPosition)(nil), // 1: com.vht.afad.afmessages.GRPCGeodeticPosition
}
var file_pkg_proto_ag_algo_RSRadar_proto_depIdxs = []int32{
	1, // 0: com.vht.afad.afmessages.GRPCRSRadar.position:type_name -> com.vht.afad.afmessages.GRPCGeodeticPosition
	1, // 1: com.vht.afad.afmessages.GRPCRSRadar.coverage:type_name -> com.vht.afad.afmessages.GRPCGeodeticPosition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_ag_algo_RSRadar_proto_init() }
func file_pkg_proto_ag_algo_RSRadar_proto_init() {
	if File_pkg_proto_ag_algo_RSRadar_proto != nil {
		return
	}
	file_pkg_proto_ag_algo_Point_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ag_algo_RSRadar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCRSRadar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ag_algo_RSRadar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ag_algo_RSRadar_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ag_algo_RSRadar_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ag_algo_RSRadar_proto_msgTypes,
	}.Build()
	File_pkg_proto_ag_algo_RSRadar_proto = out.File
	file_pkg_proto_ag_algo_RSRadar_proto_rawDesc = nil
	file_pkg_proto_ag_algo_RSRadar_proto_goTypes = nil
	file_pkg_proto_ag_algo_RSRadar_proto_depIdxs = nil
}
