// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/proto/ag_algo/RSService.proto

package ag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RSService_CalculateRS_FullMethodName       = "/com.vht.afad.afmessages.RSService/CalculateRS"
	RSService_SendRequestRS_FullMethodName     = "/com.vht.afad.afmessages.RSService/SendRequestRS"
	RSService_SendRequestListRS_FullMethodName = "/com.vht.afad.afmessages.RSService/SendRequestListRS"
)

// RSServiceClient is the client API for RSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RSServiceClient interface {
	CalculateRS(ctx context.Context, in *GRPCRSRequest, opts ...grpc.CallOption) (*GRPCRequestStatus, error)
	SendRequestRS(ctx context.Context, in *GRPCRSRequest, opts ...grpc.CallOption) (*GRPCRequestStatus, error)
	SendRequestListRS(ctx context.Context, in *GRPCRSRequestList, opts ...grpc.CallOption) (*GRPCRequestStatus, error)
}

type rSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRSServiceClient(cc grpc.ClientConnInterface) RSServiceClient {
	return &rSServiceClient{cc}
}

func (c *rSServiceClient) CalculateRS(ctx context.Context, in *GRPCRSRequest, opts ...grpc.CallOption) (*GRPCRequestStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCRequestStatus)
	err := c.cc.Invoke(ctx, RSService_CalculateRS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rSServiceClient) SendRequestRS(ctx context.Context, in *GRPCRSRequest, opts ...grpc.CallOption) (*GRPCRequestStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCRequestStatus)
	err := c.cc.Invoke(ctx, RSService_SendRequestRS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rSServiceClient) SendRequestListRS(ctx context.Context, in *GRPCRSRequestList, opts ...grpc.CallOption) (*GRPCRequestStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GRPCRequestStatus)
	err := c.cc.Invoke(ctx, RSService_SendRequestListRS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RSServiceServer is the server API for RSService service.
// All implementations must embed UnimplementedRSServiceServer
// for forward compatibility.
type RSServiceServer interface {
	CalculateRS(context.Context, *GRPCRSRequest) (*GRPCRequestStatus, error)
	SendRequestRS(context.Context, *GRPCRSRequest) (*GRPCRequestStatus, error)
	SendRequestListRS(context.Context, *GRPCRSRequestList) (*GRPCRequestStatus, error)
	mustEmbedUnimplementedRSServiceServer()
}

// UnimplementedRSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRSServiceServer struct{}

func (UnimplementedRSServiceServer) CalculateRS(context.Context, *GRPCRSRequest) (*GRPCRequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRS not implemented")
}
func (UnimplementedRSServiceServer) SendRequestRS(context.Context, *GRPCRSRequest) (*GRPCRequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestRS not implemented")
}
func (UnimplementedRSServiceServer) SendRequestListRS(context.Context, *GRPCRSRequestList) (*GRPCRequestStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestListRS not implemented")
}
func (UnimplementedRSServiceServer) mustEmbedUnimplementedRSServiceServer() {}
func (UnimplementedRSServiceServer) testEmbeddedByValue()                   {}

// UnsafeRSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RSServiceServer will
// result in compilation errors.
type UnsafeRSServiceServer interface {
	mustEmbedUnimplementedRSServiceServer()
}

func RegisterRSServiceServer(s grpc.ServiceRegistrar, srv RSServiceServer) {
	// If the following call pancis, it indicates UnimplementedRSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RSService_ServiceDesc, srv)
}

func _RSService_CalculateRS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCRSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RSServiceServer).CalculateRS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RSService_CalculateRS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RSServiceServer).CalculateRS(ctx, req.(*GRPCRSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RSService_SendRequestRS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCRSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RSServiceServer).SendRequestRS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RSService_SendRequestRS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RSServiceServer).SendRequestRS(ctx, req.(*GRPCRSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RSService_SendRequestListRS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCRSRequestList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RSServiceServer).SendRequestListRS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RSService_SendRequestListRS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RSServiceServer).SendRequestListRS(ctx, req.(*GRPCRSRequestList))
	}
	return interceptor(ctx, in, info, handler)
}

// RSService_ServiceDesc is the grpc.ServiceDesc for RSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.vht.afad.afmessages.RSService",
	HandlerType: (*RSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRS",
			Handler:    _RSService_CalculateRS_Handler,
		},
		{
			MethodName: "SendRequestRS",
			Handler:    _RSService_SendRequestRS_Handler,
		},
		{
			MethodName: "SendRequestListRS",
			Handler:    _RSService_SendRequestListRS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ag_algo/RSService.proto",
}
