// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/ag_algo/SystemParameter.proto

package ag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCSystemParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                               //
	Code              string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                           //
	Name              string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                           //
	TypeCode          string `protobuf:"bytes,4,opt,name=typeCode,proto3" json:"typeCode,omitempty"`                   //
	TypeName          string `protobuf:"bytes,5,opt,name=typeName,proto3" json:"typeName,omitempty"`                   //
	UnitOfMeasurement string `protobuf:"bytes,6,opt,name=unitOfMeasurement,proto3" json:"unitOfMeasurement,omitempty"` //
	Value             string `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`                         //
	Note              string `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`                           //
	SubcategoryId     string `protobuf:"bytes,9,opt,name=subcategoryId,proto3" json:"subcategoryId,omitempty"`         //
	SubcategoryCode   string `protobuf:"bytes,10,opt,name=subcategoryCode,proto3" json:"subcategoryCode,omitempty"`    //
	SubcategoryName   string `protobuf:"bytes,11,opt,name=subcategoryName,proto3" json:"subcategoryName,omitempty"`    //
	CategoryId        string `protobuf:"bytes,12,opt,name=categoryId,proto3" json:"categoryId,omitempty"`              //
	CategoryCode      string `protobuf:"bytes,13,opt,name=categoryCode,proto3" json:"categoryCode,omitempty"`          //
	CategoryName      string `protobuf:"bytes,14,opt,name=categoryName,proto3" json:"categoryName,omitempty"`          //
}

func (x *GRPCSystemParameter) Reset() {
	*x = GRPCSystemParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_SystemParameter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCSystemParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCSystemParameter) ProtoMessage() {}

func (x *GRPCSystemParameter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_SystemParameter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCSystemParameter.ProtoReflect.Descriptor instead.
func (*GRPCSystemParameter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_SystemParameter_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCSystemParameter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCSystemParameter) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GRPCSystemParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GRPCSystemParameter) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *GRPCSystemParameter) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *GRPCSystemParameter) GetUnitOfMeasurement() string {
	if x != nil {
		return x.UnitOfMeasurement
	}
	return ""
}

func (x *GRPCSystemParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GRPCSystemParameter) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GRPCSystemParameter) GetSubcategoryId() string {
	if x != nil {
		return x.SubcategoryId
	}
	return ""
}

func (x *GRPCSystemParameter) GetSubcategoryCode() string {
	if x != nil {
		return x.SubcategoryCode
	}
	return ""
}

func (x *GRPCSystemParameter) GetSubcategoryName() string {
	if x != nil {
		return x.SubcategoryName
	}
	return ""
}

func (x *GRPCSystemParameter) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GRPCSystemParameter) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *GRPCSystemParameter) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

var File_pkg_proto_ag_algo_SystemParameter_proto protoreflect.FileDescriptor

var file_pkg_proto_ag_algo_SystemParameter_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x2f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0xbf, 0x03, 0x0a, 0x13, 0x47, 0x52, 0x50, 0x43, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x6e,
	0x69, 0x74, 0x4f, 0x66, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x75, 0x6e, 0x69, 0x74, 0x4f, 0x66, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ag_algo_SystemParameter_proto_rawDescOnce sync.Once
	file_pkg_proto_ag_algo_SystemParameter_proto_rawDescData = file_pkg_proto_ag_algo_SystemParameter_proto_rawDesc
)

func file_pkg_proto_ag_algo_SystemParameter_proto_rawDescGZIP() []byte {
	file_pkg_proto_ag_algo_SystemParameter_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ag_algo_SystemParameter_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ag_algo_SystemParameter_proto_rawDescData)
	})
	return file_pkg_proto_ag_algo_SystemParameter_proto_rawDescData
}

var file_pkg_proto_ag_algo_SystemParameter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_ag_algo_SystemParameter_proto_goTypes = []interface{}{
	(*GRPCSystemParameter)(nil), // 0: com.vht.afad.afmessages.GRPCSystemParameter
}
var file_pkg_proto_ag_algo_SystemParameter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_ag_algo_SystemParameter_proto_init() }
func file_pkg_proto_ag_algo_SystemParameter_proto_init() {
	if File_pkg_proto_ag_algo_SystemParameter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ag_algo_SystemParameter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCSystemParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ag_algo_SystemParameter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ag_algo_SystemParameter_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ag_algo_SystemParameter_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ag_algo_SystemParameter_proto_msgTypes,
	}.Build()
	File_pkg_proto_ag_algo_SystemParameter_proto = out.File
	file_pkg_proto_ag_algo_SystemParameter_proto_rawDesc = nil
	file_pkg_proto_ag_algo_SystemParameter_proto_goTypes = nil
	file_pkg_proto_ag_algo_SystemParameter_proto_depIdxs = nil
}
