// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/ag_algo/Track.proto

package ag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          //
	Number         int32              `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`                  //
	AircraftType   string             `protobuf:"bytes,4,opt,name=aircraftType,proto3" json:"aircraftType,omitempty"`       //
	CallSign       string             `protobuf:"bytes,5,opt,name=callSign,proto3" json:"callSign,omitempty"`               //
	Geodetic       *GRPCGeodeticState `protobuf:"bytes,6,opt,name=geodetic,proto3" json:"geodetic,omitempty"`               //
	LastUpdateTime float64            `protobuf:"fixed64,7,opt,name=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"` //
}

func (x *GRPCTrack) Reset() {
	*x = GRPCTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_ag_algo_Track_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCTrack) ProtoMessage() {}

func (x *GRPCTrack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ag_algo_Track_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCTrack.ProtoReflect.Descriptor instead.
func (*GRPCTrack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ag_algo_Track_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCTrack) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GRPCTrack) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GRPCTrack) GetAircraftType() string {
	if x != nil {
		return x.AircraftType
	}
	return ""
}

func (x *GRPCTrack) GetCallSign() string {
	if x != nil {
		return x.CallSign
	}
	return ""
}

func (x *GRPCTrack) GetGeodetic() *GRPCGeodeticState {
	if x != nil {
		return x.Geodetic
	}
	return nil
}

func (x *GRPCTrack) GetLastUpdateTime() float64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

var File_pkg_proto_ag_algo_Track_proto protoreflect.FileDescriptor

var file_pkg_proto_ag_algo_Track_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x2f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61, 0x66,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x5f, 0x61, 0x6c, 0x67, 0x6f, 0x2f, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01, 0x0a, 0x09, 0x47, 0x52, 0x50, 0x43,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x0c, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x46, 0x0a,
	0x08, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x68, 0x74, 0x2e, 0x61, 0x66, 0x61, 0x64, 0x2e, 0x61,
	0x66, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x47, 0x65,
	0x6f, 0x64, 0x65, 0x74, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x67, 0x65, 0x6f,
	0x64, 0x65, 0x74, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x61, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_ag_algo_Track_proto_rawDescOnce sync.Once
	file_pkg_proto_ag_algo_Track_proto_rawDescData = file_pkg_proto_ag_algo_Track_proto_rawDesc
)

func file_pkg_proto_ag_algo_Track_proto_rawDescGZIP() []byte {
	file_pkg_proto_ag_algo_Track_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ag_algo_Track_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_ag_algo_Track_proto_rawDescData)
	})
	return file_pkg_proto_ag_algo_Track_proto_rawDescData
}

var file_pkg_proto_ag_algo_Track_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_ag_algo_Track_proto_goTypes = []interface{}{
	(*GRPCTrack)(nil),         // 0: com.vht.afad.afmessages.GRPCTrack
	(*GRPCGeodeticState)(nil), // 1: com.vht.afad.afmessages.GRPCGeodeticState
}
var file_pkg_proto_ag_algo_Track_proto_depIdxs = []int32{
	1, // 0: com.vht.afad.afmessages.GRPCTrack.geodetic:type_name -> com.vht.afad.afmessages.GRPCGeodeticState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_ag_algo_Track_proto_init() }
func file_pkg_proto_ag_algo_Track_proto_init() {
	if File_pkg_proto_ag_algo_Track_proto != nil {
		return
	}
	file_pkg_proto_ag_algo_Point_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_ag_algo_Track_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_ag_algo_Track_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ag_algo_Track_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ag_algo_Track_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ag_algo_Track_proto_msgTypes,
	}.Build()
	File_pkg_proto_ag_algo_Track_proto = out.File
	file_pkg_proto_ag_algo_Track_proto_rawDesc = nil
	file_pkg_proto_ag_algo_Track_proto_goTypes = nil
	file_pkg_proto_ag_algo_Track_proto_depIdxs = nil
}
